// 营养学词库：每个单词格式为 [英文, 音标, 中文释义, 英文例句, 例句翻译]
// 分为四大板块，每个板块下按主题分组，方便按需选择学习范围。
const VOCAB = [
  {
    id: 'biochem',
    name: '人体生化营养学',
    icon: '🧬',
    desc: '营养素、代谢与生化反应',
    groups: [
      {
        name: '基础概念',
        words: [
          ['nutrition', '/nuˈtrɪʃən/', '营养；营养学', 'Good nutrition is the foundation of good health.', '良好的营养是健康的基础。'],
          ['nutrient', '/ˈnuːtriənt/', '营养素', 'Vegetables provide many important nutrients.', '蔬菜提供许多重要的营养素。'],
          ['macronutrient', '/ˌmækroʊˈnuːtriənt/', '宏量营养素', 'Carbohydrates, proteins and fats are the three main macronutrients.', '碳水化合物、蛋白质和脂肪是三大宏量营养素。'],
          ['micronutrient', '/ˌmaɪkroʊˈnuːtriənt/', '微量营养素', 'Vitamins and minerals are called micronutrients because we need them in small amounts.', '维生素和矿物质被称为微量营养素，因为我们只需要少量。'],
          ['calorie', '/ˈkæləri/', '卡路里；热量', 'One gram of fat provides nine calories.', '一克脂肪提供九卡路里热量。'],
          ['kilocalorie', '/ˈkɪloʊˌkæləri/', '千卡', 'Food energy is usually measured in kilocalories.', '食物能量通常以千卡为单位来计量。'],
          ['energy', '/ˈenərdʒi/', '能量', 'The body gets energy from carbohydrates, fats and proteins.', '身体从碳水化合物、脂肪和蛋白质中获取能量。'],
          ['metabolism', '/məˈtæbəlɪzəm/', '新陈代谢', 'Metabolism includes all the chemical reactions in the body.', '新陈代谢包括体内所有的化学反应。'],
          ['anabolism', '/əˈnæbəlɪzəm/', '合成代谢', 'Anabolism builds large molecules such as proteins from small ones.', '合成代谢把小分子构建成蛋白质等大分子。'],
          ['catabolism', '/kəˈtæbəlɪzəm/', '分解代谢', 'Catabolism breaks down molecules to release energy.', '分解代谢分解分子以释放能量。'],
          ['diet', '/ˈdaɪət/', '饮食；膳食', 'A healthy diet includes a variety of foods.', '健康的饮食包含多种多样的食物。'],
          ['deficiency', '/dɪˈfɪʃənsi/', '缺乏（症）', 'Iron deficiency can make you feel tired.', '缺铁会让你感到疲倦。'],
          ['intake', '/ˈɪnteɪk/', '摄入量', 'Try to reduce your daily salt intake.', '尽量减少每日的盐摄入量。'],
          ['digestion', '/daɪˈdʒestʃən/', '消化', 'Digestion begins in the mouth.', '消化从口腔开始。'],
          ['absorption', '/əbˈzɔːrpʃən/', '吸收', 'Most nutrient absorption happens in the small intestine.', '大部分营养素的吸收发生在小肠。'],
          ['bioavailability', '/ˌbaɪoʊəˌveɪləˈbɪləti/', '生物利用度', 'The bioavailability of iron from meat is higher than from plants.', '肉类中铁的生物利用度高于植物。'],
          ['essential nutrient', '/ɪˈsenʃəl ˈnuːtriənt/', '必需营养素', 'An essential nutrient must come from food because the body cannot make it.', '必需营养素必须从食物中获取，因为身体无法自己合成。'],
          ['homeostasis', '/ˌhoʊmioʊˈsteɪsɪs/', '体内平衡；稳态', 'The body maintains homeostasis by keeping blood sugar stable.', '身体通过保持血糖稳定来维持稳态。'],
          ['molecule', '/ˈmɑːlɪkjuːl/', '分子', 'A glucose molecule contains six carbon atoms.', '一个葡萄糖分子含有六个碳原子。'],
          ['compound', '/ˈkɑːmpaʊnd/', '化合物', 'Water is a compound of hydrogen and oxygen.', '水是由氢和氧组成的化合物。'],
        ],
      },
      {
        name: '碳水化合物',
        words: [
          ['carbohydrate', '/ˌkɑːrboʊˈhaɪdreɪt/', '碳水化合物', 'Rice and bread are rich in carbohydrates.', '米饭和面包富含碳水化合物。'],
          ['sugar', '/ˈʃʊɡər/', '糖', 'Soft drinks contain a lot of sugar.', '软饮料含有大量的糖。'],
          ['glucose', '/ˈɡluːkoʊs/', '葡萄糖', 'Glucose is the main fuel for the brain.', '葡萄糖是大脑的主要燃料。'],
          ['fructose', '/ˈfrʌktoʊs/', '果糖', 'Fructose is the natural sugar found in fruit.', '果糖是水果中天然存在的糖。'],
          ['galactose', '/ɡəˈlæktoʊs/', '半乳糖', 'Lactose is made of glucose and galactose.', '乳糖由葡萄糖和半乳糖组成。'],
          ['sucrose', '/ˈsuːkroʊs/', '蔗糖', 'Table sugar is sucrose.', '餐桌上的白糖就是蔗糖。'],
          ['lactose', '/ˈlæktoʊs/', '乳糖', 'Milk contains a sugar called lactose.', '牛奶含有一种叫乳糖的糖。'],
          ['maltose', '/ˈmɔːltoʊs/', '麦芽糖', 'Maltose is produced when starch is broken down.', '淀粉分解时会产生麦芽糖。'],
          ['monosaccharide', '/ˌmɑːnoʊˈsækəraɪd/', '单糖', 'Glucose is a monosaccharide, the simplest form of sugar.', '葡萄糖是一种单糖，是糖最简单的形式。'],
          ['disaccharide', '/daɪˈsækəraɪd/', '双糖', 'Sucrose is a disaccharide made of two sugar units.', '蔗糖是由两个糖单位组成的双糖。'],
          ['polysaccharide', '/ˌpɑːliˈsækəraɪd/', '多糖', 'Starch is a polysaccharide made of many glucose units.', '淀粉是由许多葡萄糖单位组成的多糖。'],
          ['starch', '/stɑːrtʃ/', '淀粉', 'Potatoes are a good source of starch.', '土豆是淀粉的良好来源。'],
          ['glycogen', '/ˈɡlaɪkədʒən/', '糖原', 'The liver and muscles store glucose as glycogen.', '肝脏和肌肉以糖原的形式储存葡萄糖。'],
          ['dietary fiber', '/ˈdaɪəteri ˈfaɪbər/', '膳食纤维', 'Dietary fiber helps keep your digestive system healthy.', '膳食纤维有助于保持消化系统健康。'],
          ['soluble fiber', '/ˈsɑːljəbəl ˈfaɪbər/', '可溶性纤维', 'Oats contain soluble fiber that can lower cholesterol.', '燕麦含有能降低胆固醇的可溶性纤维。'],
          ['cellulose', '/ˈseljəloʊs/', '纤维素', 'Humans cannot digest cellulose.', '人类无法消化纤维素。'],
          ['glycemic index', '/ɡlaɪˈsiːmɪk ˈɪndeks/', '血糖生成指数（GI）', 'White bread has a high glycemic index.', '白面包的血糖生成指数很高。'],
          ['blood glucose', '/blʌd ˈɡluːkoʊs/', '血糖', 'Blood glucose rises after a meal.', '饭后血糖会升高。'],
          ['insulin', '/ˈɪnsəlɪn/', '胰岛素', 'Insulin helps cells take up glucose from the blood.', '胰岛素帮助细胞从血液中摄取葡萄糖。'],
          ['glucagon', '/ˈɡluːkəɡɑːn/', '胰高血糖素', 'Glucagon raises blood sugar when it is too low.', '血糖过低时，胰高血糖素会使其升高。'],
        ],
      },
      {
        name: '蛋白质',
        words: [
          ['protein', '/ˈproʊtiːn/', '蛋白质', 'Eggs are an excellent source of protein.', '鸡蛋是蛋白质的极佳来源。'],
          ['amino acid', '/əˈmiːnoʊ ˈæsɪd/', '氨基酸', 'Proteins are made of amino acids.', '蛋白质由氨基酸组成。'],
          ['essential amino acid', '/ɪˈsenʃəl əˈmiːnoʊ ˈæsɪd/', '必需氨基酸', 'There are nine essential amino acids that we must get from food.', '有九种必需氨基酸必须从食物中获取。'],
          ['peptide', '/ˈpeptaɪd/', '肽', 'A peptide is a short chain of amino acids.', '肽是由氨基酸组成的短链。'],
          ['peptide bond', '/ˈpeptaɪd bɑːnd/', '肽键', 'A peptide bond links two amino acids together.', '肽键把两个氨基酸连接在一起。'],
          ['enzyme', '/ˈenzaɪm/', '酶', 'Enzymes speed up chemical reactions in the body.', '酶能加快体内的化学反应。'],
          ['complete protein', '/kəmˈpliːt ˈproʊtiːn/', '完全蛋白质', 'Soy is a complete protein that contains all essential amino acids.', '大豆是含有全部必需氨基酸的完全蛋白质。'],
          ['nitrogen balance', '/ˈnaɪtrədʒən ˈbæləns/', '氮平衡', 'Growing children are usually in positive nitrogen balance.', '正在生长的儿童通常处于正氮平衡。'],
          ['leucine', '/ˈluːsiːn/', '亮氨酸', 'Leucine plays a key role in building muscle.', '亮氨酸在肌肉构建中起关键作用。'],
          ['glutamine', '/ˈɡluːtəmiːn/', '谷氨酰胺', 'Glutamine is an important fuel for gut cells.', '谷氨酰胺是肠道细胞的重要燃料。'],
          ['collagen', '/ˈkɑːlədʒən/', '胶原蛋白', 'Collagen is the most abundant protein in the body.', '胶原蛋白是人体中含量最多的蛋白质。'],
          ['denaturation', '/diːˌneɪtʃəˈreɪʃən/', '（蛋白质）变性', 'Cooking an egg causes denaturation of its proteins.', '煮鸡蛋会导致其中的蛋白质变性。'],
          ['antibody', '/ˈæntiˌbɑːdi/', '抗体', 'An antibody is a protein that helps fight infection.', '抗体是一种帮助抵抗感染的蛋白质。'],
          ['urea', '/juˈriːə/', '尿素', 'The liver converts excess nitrogen into urea.', '肝脏把多余的氮转化为尿素。'],
        ],
      },
      {
        name: '脂类',
        words: [
          ['lipid', '/ˈlɪpɪd/', '脂质', 'Fats and oils are types of lipids.', '脂肪和油都是脂质的类型。'],
          ['fat', '/fæt/', '脂肪', 'Avocados contain healthy fat.', '牛油果含有健康的脂肪。'],
          ['fatty acid', '/ˈfæti ˈæsɪd/', '脂肪酸', 'A fatty acid is a building block of fat.', '脂肪酸是脂肪的组成单位。'],
          ['saturated fat', '/ˈsætʃəreɪtɪd fæt/', '饱和脂肪', 'Butter is high in saturated fat.', '黄油的饱和脂肪含量很高。'],
          ['unsaturated fat', '/ʌnˈsætʃəreɪtɪd fæt/', '不饱和脂肪', 'Olive oil is rich in unsaturated fat.', '橄榄油富含不饱和脂肪。'],
          ['monounsaturated', '/ˌmɑːnoʊʌnˈsætʃəreɪtɪd/', '单不饱和的', 'Nuts contain monounsaturated fats.', '坚果含有单不饱和脂肪。'],
          ['polyunsaturated', '/ˌpɑːliʌnˈsætʃəreɪtɪd/', '多不饱和的', 'Fish oil contains polyunsaturated fats.', '鱼油含有多不饱和脂肪。'],
          ['trans fat', '/trænz fæt/', '反式脂肪', 'Trans fat raises the risk of heart disease.', '反式脂肪会增加心脏病风险。'],
          ['omega-3 fatty acid', '/oʊˈmeɪɡə θriː ˈfæti ˈæsɪd/', 'ω-3脂肪酸', 'Salmon is rich in omega-3 fatty acids.', '三文鱼富含ω-3脂肪酸。'],
          ['triglyceride', '/traɪˈɡlɪsəraɪd/', '甘油三酯', 'Most fat in food and in the body is stored as triglycerides.', '食物和身体中的大部分脂肪以甘油三酯的形式存在。'],
          ['glycerol', '/ˈɡlɪsərɔːl/', '甘油', 'A triglyceride contains one glycerol and three fatty acids.', '一个甘油三酯含有一个甘油和三个脂肪酸。'],
          ['cholesterol', '/kəˈlestərɔːl/', '胆固醇', 'Egg yolks contain cholesterol.', '蛋黄含有胆固醇。'],
          ['phospholipid', '/ˌfɑːsfoʊˈlɪpɪd/', '磷脂', 'Cell membranes are made mainly of phospholipids.', '细胞膜主要由磷脂构成。'],
          ['lipoprotein', '/ˌlɪpoʊˈproʊtiːn/', '脂蛋白', 'A lipoprotein carries fat through the blood.', '脂蛋白在血液中运输脂肪。'],
          ['low-density lipoprotein', '/ˌloʊ ˈdensəti ˌlɪpoʊˈproʊtiːn/', '低密度脂蛋白（LDL，“坏”胆固醇）', 'High levels of low-density lipoprotein increase heart disease risk.', '低密度脂蛋白水平过高会增加心脏病风险。'],
          ['high-density lipoprotein', '/ˌhaɪ ˈdensəti ˌlɪpoʊˈproʊtiːn/', '高密度脂蛋白（HDL，“好”胆固醇）', 'High-density lipoprotein helps remove cholesterol from the blood.', '高密度脂蛋白有助于清除血液中的胆固醇。'],
          ['ketone body', '/ˈkiːtoʊn ˈbɑːdi/', '酮体', 'The liver makes ketone bodies when carbohydrate intake is very low.', '当碳水摄入极低时，肝脏会生成酮体。'],
        ],
      },
      {
        name: '维生素',
        words: [
          ['vitamin', '/ˈvaɪtəmɪn/', '维生素', 'Oranges are a good source of vitamin C.', '橙子是维生素C的良好来源。'],
          ['fat-soluble', '/ˈfæt ˌsɑːljəbəl/', '脂溶性的', 'Vitamins A, D, E and K are fat-soluble.', '维生素A、D、E、K是脂溶性的。'],
          ['water-soluble', '/ˈwɔːtər ˌsɑːljəbəl/', '水溶性的', 'B vitamins and vitamin C are water-soluble.', 'B族维生素和维生素C是水溶性的。'],
          ['thiamine', '/ˈθaɪəmɪn/', '硫胺素（维生素B1）', 'Thiamine helps the body turn carbohydrates into energy.', '硫胺素帮助身体把碳水化合物转化为能量。'],
          ['riboflavin', '/ˌraɪboʊˈfleɪvɪn/', '核黄素（维生素B2）', 'Milk is a good source of riboflavin.', '牛奶是核黄素的良好来源。'],
          ['niacin', '/ˈnaɪəsɪn/', '烟酸（维生素B3）', 'A lack of niacin causes a disease called pellagra.', '缺乏烟酸会导致一种叫糙皮病的疾病。'],
          ['pyridoxine', '/ˌpɪrɪˈdɑːksiːn/', '吡哆醇（维生素B6）', 'Pyridoxine is needed for protein metabolism.', '蛋白质代谢需要吡哆醇。'],
          ['folate', '/ˈfoʊleɪt/', '叶酸（维生素B9）', 'Pregnant women need extra folate.', '孕妇需要额外补充叶酸。'],
          ['cobalamin', '/koʊˈbæləmɪn/', '钴胺素（维生素B12）', 'Vegans may need to take cobalamin supplements.', '纯素食者可能需要补充钴胺素。'],
          ['biotin', '/ˈbaɪətɪn/', '生物素', 'Biotin helps the body use fats and carbohydrates.', '生物素帮助身体利用脂肪和碳水化合物。'],
          ['ascorbic acid', '/əˈskɔːrbɪk ˈæsɪd/', '抗坏血酸（维生素C）', 'Ascorbic acid improves the absorption of iron.', '抗坏血酸能促进铁的吸收。'],
          ['retinol', '/ˈretɪnɔːl/', '视黄醇（维生素A）', 'Retinol is important for good vision.', '视黄醇对良好的视力很重要。'],
          ['beta-carotene', '/ˌbeɪtə ˈkærətiːn/', 'β-胡萝卜素', 'Carrots are rich in beta-carotene.', '胡萝卜富含β-胡萝卜素。'],
          ['vitamin D', '/ˈvaɪtəmɪn diː/', '维生素D', 'Your skin makes vitamin D when exposed to sunlight.', '皮肤在阳光照射下会合成维生素D。'],
          ['tocopherol', '/toʊˈkɑːfərɔːl/', '生育酚（维生素E）', 'Tocopherol acts as an antioxidant in cell membranes.', '生育酚在细胞膜中起抗氧化作用。'],
          ['vitamin K', '/ˈvaɪtəmɪn keɪ/', '维生素K', 'Vitamin K is necessary for blood clotting.', '维生素K是血液凝固所必需的。'],
          ['scurvy', '/ˈskɜːrvi/', '坏血病', 'Sailors used to get scurvy because they ate no fresh fruit.', '过去水手因吃不到新鲜水果而患坏血病。'],
          ['rickets', '/ˈrɪkɪts/', '佝偻病', 'Rickets is caused by a lack of vitamin D in children.', '佝偻病是儿童缺乏维生素D引起的。'],
        ],
      },
      {
        name: '矿物质',
        words: [
          ['mineral', '/ˈmɪnərəl/', '矿物质', 'Calcium is the most abundant mineral in the body.', '钙是人体中含量最多的矿物质。'],
          ['calcium', '/ˈkælsiəm/', '钙', 'Dairy products are high in calcium.', '乳制品含钙量高。'],
          ['phosphorus', '/ˈfɑːsfərəs/', '磷', 'Phosphorus works with calcium to build strong bones.', '磷与钙一起构建强壮的骨骼。'],
          ['magnesium', '/mæɡˈniːziəm/', '镁', 'Leafy greens and nuts are good sources of magnesium.', '绿叶菜和坚果是镁的良好来源。'],
          ['sodium', '/ˈsoʊdiəm/', '钠', 'Processed foods are often high in sodium.', '加工食品通常含钠量高。'],
          ['potassium', '/pəˈtæsiəm/', '钾', 'Bananas are famous for their potassium.', '香蕉以富含钾而闻名。'],
          ['chloride', '/ˈklɔːraɪd/', '氯化物；氯离子', 'Table salt is made of sodium and chloride.', '食盐由钠和氯离子组成。'],
          ['iron', '/ˈaɪərn/', '铁', 'Red meat is a rich source of iron.', '红肉是铁的丰富来源。'],
          ['heme iron', '/hiːm ˈaɪərn/', '血红素铁', 'Heme iron from meat is absorbed more easily than plant iron.', '肉类中的血红素铁比植物中的铁更容易吸收。'],
          ['zinc', '/zɪŋk/', '锌', 'Zinc supports the immune system.', '锌能支持免疫系统。'],
          ['iodine', '/ˈaɪədaɪn/', '碘', 'Iodine is added to salt to prevent thyroid problems.', '盐中加碘以预防甲状腺问题。'],
          ['selenium', '/səˈliːniəm/', '硒', 'Brazil nuts are very high in selenium.', '巴西坚果的硒含量非常高。'],
          ['copper', '/ˈkɑːpər/', '铜', 'Copper helps the body use iron.', '铜帮助身体利用铁。'],
          ['fluoride', '/ˈflɔːraɪd/', '氟化物', 'Fluoride helps prevent tooth decay.', '氟化物有助于预防蛀牙。'],
          ['electrolyte', '/ɪˈlektrəlaɪt/', '电解质', 'Sodium and potassium are important electrolytes.', '钠和钾是重要的电解质。'],
          ['trace element', '/treɪs ˈelɪmənt/', '微量元素', 'Zinc is a trace element needed in very small amounts.', '锌是一种只需极少量的微量元素。'],
        ],
      },
      {
        name: '代谢过程',
        words: [
          ['glycolysis', '/ɡlaɪˈkɑːləsɪs/', '糖酵解', 'Glycolysis breaks glucose into two smaller molecules.', '糖酵解把葡萄糖分解成两个更小的分子。'],
          ['citric acid cycle', '/ˈsɪtrɪk ˈæsɪd ˈsaɪkəl/', '柠檬酸循环（三羧酸循环）', 'The citric acid cycle takes place in the mitochondria.', '柠檬酸循环在线粒体中进行。'],
          ['gluconeogenesis', '/ˌɡluːkoʊˌniːoʊˈdʒenəsɪs/', '糖异生', 'During fasting, the liver makes new glucose through gluconeogenesis.', '禁食期间，肝脏通过糖异生合成新的葡萄糖。'],
          ['lipolysis', '/lɪˈpɑːləsɪs/', '脂肪分解', 'Exercise increases lipolysis in fat cells.', '运动会增加脂肪细胞中的脂肪分解。'],
          ['beta-oxidation', '/ˌbeɪtə ˌɑːksɪˈdeɪʃən/', 'β-氧化', 'Fatty acids are broken down by beta-oxidation.', '脂肪酸通过β-氧化被分解。'],
          ['oxidation', '/ˌɑːksɪˈdeɪʃən/', '氧化', 'The oxidation of nutrients releases energy.', '营养素的氧化会释放能量。'],
          ['hydrolysis', '/haɪˈdrɑːləsɪs/', '水解', 'Digestive enzymes break down food by hydrolysis.', '消化酶通过水解分解食物。'],
          ['adenosine triphosphate', '/əˈdenəsiːn traɪˈfɑːsfeɪt/', '三磷酸腺苷（ATP）', 'Adenosine triphosphate is the energy currency of the cell.', '三磷酸腺苷是细胞的能量货币。'],
          ['mitochondria', '/ˌmaɪtəˈkɑːndriə/', '线粒体', 'Mitochondria are called the powerhouses of the cell.', '线粒体被称为细胞的动力工厂。'],
          ['coenzyme', '/koʊˈenzaɪm/', '辅酶', 'Many B vitamins act as coenzymes.', '许多B族维生素起辅酶的作用。'],
          ['hormone', '/ˈhɔːrmoʊn/', '激素', 'Insulin is a hormone made by the pancreas.', '胰岛素是胰腺分泌的一种激素。'],
          ['antioxidant', '/ˌæntiˈɑːksɪdənt/', '抗氧化剂', 'Berries are full of antioxidants.', '浆果富含抗氧化剂。'],
          ['free radical', '/friː ˈrædɪkəl/', '自由基', 'A free radical can damage cells.', '自由基会损伤细胞。'],
          ['oxidative stress', '/ˈɑːksɪdeɪtɪv stres/', '氧化应激', 'Smoking increases oxidative stress in the body.', '吸烟会增加体内的氧化应激。'],
          ['ketosis', '/kiːˈtoʊsɪs/', '酮症', 'A very low-carb diet can put the body into ketosis.', '极低碳水饮食会使身体进入酮症状态。'],
          ['inflammation', '/ˌɪnfləˈmeɪʃən/', '炎症', 'A poor diet may increase inflammation.', '不良饮食可能加重炎症。'],
        ],
      },
    ],
  },
  {
    id: 'anatomy',
    name: '解剖学',
    icon: '🫀',
    desc: '人体结构与器官系统',
    groups: [
      {
        name: '基础结构',
        words: [
          ['anatomy', '/əˈnætəmi/', '解剖学', 'Anatomy is the study of the structure of the body.', '解剖学是研究身体结构的学科。'],
          ['physiology', '/ˌfɪziˈɑːlədʒi/', '生理学', 'Physiology explains how the body works.', '生理学解释身体是如何运作的。'],
          ['cell', '/sel/', '细胞', 'The cell is the basic unit of life.', '细胞是生命的基本单位。'],
          ['tissue', '/ˈtɪʃuː/', '组织', 'Muscle tissue can contract.', '肌肉组织能够收缩。'],
          ['organ', '/ˈɔːrɡən/', '器官', 'The skin is the largest organ of the body.', '皮肤是人体最大的器官。'],
          ['organ system', '/ˈɔːrɡən ˈsɪstəm/', '器官系统', 'Each organ system has a special job.', '每个器官系统都有特定的功能。'],
          ['cell membrane', '/sel ˈmembreɪn/', '细胞膜', 'The cell membrane controls what enters the cell.', '细胞膜控制物质进入细胞。'],
          ['epithelium', '/ˌepɪˈθiːliəm/', '上皮（组织）', 'The intestinal epithelium absorbs nutrients.', '肠上皮负责吸收营养素。'],
          ['connective tissue', '/kəˈnektɪv ˈtɪʃuː/', '结缔组织', 'Bone and blood are types of connective tissue.', '骨骼和血液都属于结缔组织。'],
          ['receptor', '/rɪˈseptər/', '受体', 'Insulin binds to a receptor on the cell surface.', '胰岛素与细胞表面的受体结合。'],
        ],
      },
      {
        name: '消化系统',
        words: [
          ['digestive system', '/daɪˈdʒestɪv ˈsɪstəm/', '消化系统', 'The digestive system breaks food into nutrients.', '消化系统把食物分解成营养素。'],
          ['gastrointestinal tract', '/ˌɡæstroʊɪnˈtestɪnəl trækt/', '胃肠道（GI道）', 'The gastrointestinal tract runs from the mouth to the anus.', '胃肠道从口腔一直延伸到肛门。'],
          ['saliva', '/səˈlaɪvə/', '唾液', 'Saliva starts the digestion of starch.', '唾液开始对淀粉进行消化。'],
          ['salivary amylase', '/ˈsæləveri ˈæmɪleɪs/', '唾液淀粉酶', 'Salivary amylase breaks down starch in the mouth.', '唾液淀粉酶在口腔中分解淀粉。'],
          ['bolus', '/ˈboʊləs/', '食团', 'Chewed food forms a soft bolus before swallowing.', '咀嚼后的食物在吞咽前形成柔软的食团。'],
          ['esophagus', '/ɪˈsɑːfəɡəs/', '食道', 'The esophagus carries food from the mouth to the stomach.', '食道把食物从口腔送到胃。'],
          ['stomach', '/ˈstʌmək/', '胃', 'The stomach mixes food with acid.', '胃把食物与胃酸混合。'],
          ['gastric juice', '/ˈɡæstrɪk dʒuːs/', '胃液', 'Gastric juice contains acid and enzymes.', '胃液含有酸和酶。'],
          ['hydrochloric acid', '/ˌhaɪdrəˈklɔːrɪk ˈæsɪd/', '盐酸（胃酸）', 'Hydrochloric acid in the stomach kills many bacteria.', '胃里的盐酸能杀死许多细菌。'],
          ['pepsin', '/ˈpepsɪn/', '胃蛋白酶', 'Pepsin begins the digestion of protein.', '胃蛋白酶开始对蛋白质进行消化。'],
          ['chyme', '/kaɪm/', '食糜', 'The stomach turns food into a thick liquid called chyme.', '胃把食物变成一种叫食糜的浓稠液体。'],
          ['sphincter', '/ˈsfɪŋktər/', '括约肌', 'A sphincter at the bottom of the esophagus stops acid from coming back up.', '食道底部的括约肌阻止胃酸反流。'],
          ['small intestine', '/smɔːl ɪnˈtestɪn/', '小肠', 'The small intestine is about six meters long.', '小肠大约有六米长。'],
          ['duodenum', '/ˌduːəˈdiːnəm/', '十二指肠', 'The duodenum is the first part of the small intestine.', '十二指肠是小肠的第一段。'],
          ['jejunum', '/dʒɪˈdʒuːnəm/', '空肠', 'Most nutrients are absorbed in the jejunum.', '大多数营养素在空肠被吸收。'],
          ['ileum', '/ˈɪliəm/', '回肠', 'Vitamin B12 is absorbed in the ileum.', '维生素B12在回肠被吸收。'],
          ['villi', '/ˈvɪlaɪ/', '绒毛（复数）', 'Villi increase the surface area of the small intestine.', '绒毛增加了小肠的表面积。'],
          ['microvilli', '/ˌmaɪkroʊˈvɪlaɪ/', '微绒毛', 'Microvilli cover the surface of intestinal cells.', '微绒毛覆盖在肠细胞表面。'],
          ['large intestine', '/lɑːrdʒ ɪnˈtestɪn/', '大肠', 'The large intestine absorbs water.', '大肠吸收水分。'],
          ['colon', '/ˈkoʊlən/', '结肠', 'Fiber feeds the bacteria in the colon.', '纤维为结肠中的细菌提供养分。'],
          ['rectum', '/ˈrektəm/', '直肠', 'The rectum stores waste before it leaves the body.', '直肠在废物排出体外前将其储存。'],
          ['pancreas', '/ˈpæŋkriəs/', '胰腺', 'The pancreas makes digestive enzymes and insulin.', '胰腺分泌消化酶和胰岛素。'],
          ['liver', '/ˈlɪvər/', '肝脏', 'The liver processes nutrients after absorption.', '肝脏在营养素被吸收后对其进行加工。'],
          ['gallbladder', '/ˈɡɔːlˌblædər/', '胆囊', 'The gallbladder stores bile.', '胆囊储存胆汁。'],
          ['bile', '/baɪl/', '胆汁', 'Bile helps digest fat.', '胆汁帮助消化脂肪。'],
          ['peristalsis', '/ˌperɪˈstɔːlsɪs/', '（肠胃）蠕动', 'Peristalsis moves food through the digestive tract.', '蠕动推动食物在消化道中前进。'],
          ['gut microbiota', '/ɡʌt ˌmaɪkroʊbaɪˈoʊtə/', '肠道菌群', 'A high-fiber diet supports a healthy gut microbiota.', '高纤维饮食有助于维持健康的肠道菌群。'],
        ],
      },
      {
        name: '循环与呼吸',
        words: [
          ['circulatory system', '/ˈsɜːrkjələtɔːri ˈsɪstəm/', '循环系统', 'The circulatory system delivers nutrients to every cell.', '循环系统把营养素输送到每个细胞。'],
          ['heart', '/hɑːrt/', '心脏', 'The heart pumps blood around the body.', '心脏把血液泵送到全身。'],
          ['artery', '/ˈɑːrtəri/', '动脉', 'An artery carries blood away from the heart.', '动脉把血液从心脏运出。'],
          ['vein', '/veɪn/', '静脉', 'A vein carries blood back to the heart.', '静脉把血液运回心脏。'],
          ['capillary', '/ˈkæpəleri/', '毛细血管', 'Nutrients pass from capillaries into the tissues.', '营养素从毛细血管进入组织。'],
          ['portal vein', '/ˈpɔːrtəl veɪn/', '门静脉', 'The portal vein carries nutrients from the intestine to the liver.', '门静脉把营养素从肠道输送到肝脏。'],
          ['plasma', '/ˈplæzmə/', '血浆', 'Plasma is the liquid part of blood.', '血浆是血液的液体部分。'],
          ['red blood cell', '/red blʌd sel/', '红细胞', 'Each red blood cell carries oxygen.', '每个红细胞都携带氧气。'],
          ['hemoglobin', '/ˈhiːməɡloʊbɪn/', '血红蛋白', 'Iron is needed to make hemoglobin.', '合成血红蛋白需要铁。'],
          ['blood pressure', '/blʌd ˈpreʃər/', '血压', 'Too much salt can raise blood pressure.', '盐摄入过多会升高血压。'],
          ['lymphatic system', '/lɪmˈfætɪk ˈsɪstəm/', '淋巴系统', 'Absorbed fats enter the lymphatic system first.', '被吸收的脂肪首先进入淋巴系统。'],
          ['respiratory system', '/ˈrespərətɔːri ˈsɪstəm/', '呼吸系统', 'The respiratory system brings oxygen into the body.', '呼吸系统把氧气带入体内。'],
          ['lung', '/lʌŋ/', '肺', 'Oxygen enters the blood in the lungs.', '氧气在肺部进入血液。'],
          ['oxygen', '/ˈɑːksɪdʒən/', '氧气', 'Muscles need oxygen to burn fat.', '肌肉需要氧气来燃烧脂肪。'],
          ['carbon dioxide', '/ˈkɑːrbən daɪˈɑːksaɪd/', '二氧化碳', 'We breathe out carbon dioxide.', '我们呼出二氧化碳。'],
        ],
      },
      {
        name: '内分泌与泌尿',
        words: [
          ['endocrine system', '/ˈendəkrɪn ˈsɪstəm/', '内分泌系统', 'The endocrine system uses hormones to send messages.', '内分泌系统利用激素传递信息。'],
          ['gland', '/ɡlænd/', '腺体', 'A gland makes and releases substances such as hormones.', '腺体分泌和释放激素等物质。'],
          ['thyroid', '/ˈθaɪrɔɪd/', '甲状腺', 'The thyroid controls your metabolic rate.', '甲状腺控制着你的代谢速率。'],
          ['adrenal gland', '/əˈdriːnəl ɡlænd/', '肾上腺', 'The adrenal gland releases adrenaline during stress.', '肾上腺在压力下释放肾上腺素。'],
          ['pituitary gland', '/pɪˈtuːɪteri ɡlænd/', '垂体', 'The pituitary gland is often called the master gland.', '垂体常被称为“主腺体”。'],
          ['hypothalamus', '/ˌhaɪpoʊˈθæləməs/', '下丘脑', 'The hypothalamus helps control hunger and thirst.', '下丘脑帮助控制饥饿和口渴。'],
          ['cortisol', '/ˈkɔːrtɪsɔːl/', '皮质醇', 'Cortisol levels rise when you are stressed.', '压力大时皮质醇水平会升高。'],
          ['leptin', '/ˈleptɪn/', '瘦素', 'Leptin tells the brain that you have enough stored fat.', '瘦素告诉大脑体内储存的脂肪已经足够。'],
          ['ghrelin', '/ˈɡrelɪn/', '饥饿素（胃饥饿素）', 'Ghrelin makes you feel hungry.', '饥饿素会让你感到饥饿。'],
          ['urinary system', '/ˈjʊrəneri ˈsɪstəm/', '泌尿系统', 'The urinary system removes waste from the blood.', '泌尿系统清除血液中的废物。'],
          ['kidney', '/ˈkɪdni/', '肾脏', 'The kidney filters about 180 liters of blood plasma a day.', '肾脏每天过滤大约180升血浆。'],
          ['nephron', '/ˈnefrɑːn/', '肾单位', 'Each kidney contains about one million nephrons.', '每个肾脏含有约一百万个肾单位。'],
          ['urine', '/ˈjʊrɪn/', '尿液', 'Pale yellow urine is a sign of good hydration.', '淡黄色的尿液是水分充足的标志。'],
        ],
      },
      {
        name: '肌肉骨骼与神经免疫',
        words: [
          ['skeletal system', '/ˈskelətəl ˈsɪstəm/', '骨骼系统', 'The skeletal system supports and protects the body.', '骨骼系统支撑和保护身体。'],
          ['bone', '/boʊn/', '骨', 'Calcium and vitamin D keep bone strong.', '钙和维生素D使骨骼强壮。'],
          ['bone mineral density', '/boʊn ˈmɪnərəl ˈdensəti/', '骨密度', 'Weight-bearing exercise improves bone mineral density.', '负重运动能提高骨密度。'],
          ['cartilage', '/ˈkɑːrtəlɪdʒ/', '软骨', 'Cartilage protects the ends of bones in a joint.', '软骨保护关节中骨的末端。'],
          ['joint', '/dʒɔɪnt/', '关节', 'The knee is the largest joint in the body.', '膝盖是人体最大的关节。'],
          ['skeletal muscle', '/ˈskelətəl ˈmʌsəl/', '骨骼肌', 'Skeletal muscle stores a lot of glycogen.', '骨骼肌储存大量糖原。'],
          ['muscle fiber', '/ˈmʌsəl ˈfaɪbər/', '肌纤维', 'Each muscle fiber is a long, thin cell.', '每条肌纤维都是一个细长的细胞。'],
          ['tendon', '/ˈtendən/', '肌腱', 'A tendon connects muscle to bone.', '肌腱把肌肉连接到骨骼上。'],
          ['ligament', '/ˈlɪɡəmənt/', '韧带', 'A ligament connects bone to bone.', '韧带把骨与骨连接起来。'],
          ['adipose tissue', '/ˈædɪpoʊs ˈtɪʃuː/', '脂肪组织', 'Adipose tissue stores energy as fat.', '脂肪组织以脂肪的形式储存能量。'],
          ['nervous system', '/ˈnɜːrvəs ˈsɪstəm/', '神经系统', 'The nervous system controls muscle movement.', '神经系统控制肌肉运动。'],
          ['brain', '/breɪn/', '大脑', 'The brain uses about 20 percent of the body\'s energy.', '大脑消耗身体约20%的能量。'],
          ['neuron', '/ˈnʊrɑːn/', '神经元', 'A neuron sends electrical signals.', '神经元传递电信号。'],
          ['spinal cord', '/ˈspaɪnəl kɔːrd/', '脊髓', 'The spinal cord connects the brain to the rest of the body.', '脊髓把大脑与身体其他部位连接起来。'],
          ['immune system', '/ɪˈmjuːn ˈsɪstəm/', '免疫系统', 'Good nutrition supports a strong immune system.', '良好的营养支持强大的免疫系统。'],
        ],
      },
    ],
  },
  {
    id: 'food',
    name: '食物营养学',
    icon: '🥦',
    desc: '食物分类、成分、标签与食品安全',
    groups: [
      {
        name: '食物分类',
        words: [
          ['whole grain', '/hoʊl ɡreɪn/', '全谷物', 'Brown rice is a whole grain.', '糙米是一种全谷物。'],
          ['refined grain', '/rɪˈfaɪnd ɡreɪn/', '精制谷物', 'White flour is a refined grain with the bran removed.', '白面粉是去除了麸皮的精制谷物。'],
          ['cereal', '/ˈsɪriəl/', '谷物；麦片', 'Wheat, rice and corn are cereal crops.', '小麦、水稻和玉米都是谷类作物。'],
          ['legume', '/ˈleɡjuːm/', '豆类', 'Lentils and chickpeas are legumes.', '小扁豆和鹰嘴豆都是豆类。'],
          ['soybean', '/ˈsɔɪbiːn/', '大豆', 'Tofu is made from soybeans.', '豆腐是用大豆做的。'],
          ['tofu', '/ˈtoʊfuː/', '豆腐', 'Tofu is a good plant protein.', '豆腐是一种优质植物蛋白。'],
          ['vegetable', '/ˈvedʒtəbəl/', '蔬菜', 'Try to fill half your plate with vegetables.', '尽量让蔬菜占满盘子的一半。'],
          ['leafy green', '/ˈliːfi ɡriːn/', '绿叶蔬菜', 'Spinach is a leafy green rich in folate.', '菠菜是一种富含叶酸的绿叶蔬菜。'],
          ['cruciferous vegetable', '/kruːˈsɪfərəs ˈvedʒtəbəl/', '十字花科蔬菜', 'Broccoli is a cruciferous vegetable.', '西兰花是一种十字花科蔬菜。'],
          ['tuber', '/ˈtuːbər/', '块茎类（食物）', 'The potato is a tuber that grows underground.', '土豆是一种生长在地下的块茎。'],
          ['fruit', '/fruːt/', '水果', 'Whole fruit is better than fruit juice.', '完整的水果比果汁更好。'],
          ['berry', '/ˈberi/', '浆果', 'A blueberry is a small berry full of antioxidants.', '蓝莓是一种富含抗氧化剂的小浆果。'],
          ['nut', '/nʌt/', '坚果', 'A handful of nuts makes a healthy snack.', '一小把坚果是健康的零食。'],
          ['seed', '/siːd/', '种子', 'Chia seeds are high in fiber.', '奇亚籽富含纤维。'],
          ['dairy', '/ˈderi/', '乳制品', 'Milk, cheese and yogurt are dairy foods.', '牛奶、奶酪和酸奶都是乳制品。'],
          ['poultry', '/ˈpoʊltri/', '禽肉；家禽', 'Chicken and turkey are types of poultry.', '鸡肉和火鸡肉都属于禽肉。'],
          ['seafood', '/ˈsiːfuːd/', '海鲜', 'Seafood is a good source of iodine.', '海鲜是碘的良好来源。'],
          ['lean meat', '/liːn miːt/', '瘦肉', 'Lean meat has less fat.', '瘦肉的脂肪较少。'],
          ['red meat', '/red miːt/', '红肉', 'Beef and pork are red meat.', '牛肉和猪肉都是红肉。'],
          ['processed meat', '/ˈprɑːsest miːt/', '加工肉制品', 'Bacon and sausage are processed meat.', '培根和香肠都是加工肉制品。'],
          ['fermented food', '/fərˈmentɪd fuːd/', '发酵食品', 'Kimchi is a fermented food.', '泡菜是一种发酵食品。'],
          ['ultra-processed food', '/ˌʌltrə ˈprɑːsest fuːd/', '超加工食品', 'Chips and candy are ultra-processed foods.', '薯片和糖果都是超加工食品。'],
          ['whole food', '/hoʊl fuːd/', '天然完整食物（未加工食物）', 'An apple is a whole food.', '苹果是一种未经加工的天然完整食物。'],
        ],
      },
      {
        name: '食物成分',
        words: [
          ['bran', '/bræn/', '麸皮', 'Bran is the outer layer of the grain and is rich in fiber.', '麸皮是谷粒的外层，富含纤维。'],
          ['germ', '/dʒɜːrm/', '胚芽', 'The germ is the part of the grain that can grow into a new plant.', '胚芽是谷粒中能长成新植株的部分。'],
          ['endosperm', '/ˈendoʊspɜːrm/', '胚乳', 'White flour is made mostly from the endosperm.', '白面粉主要由胚乳制成。'],
          ['gluten', '/ˈɡluːtən/', '麸质；面筋', 'People with celiac disease must avoid gluten.', '乳糜泻患者必须避免麸质。'],
          ['phytochemical', '/ˌfaɪtoʊˈkemɪkəl/', '植物化学物', 'Colorful vegetables contain many phytochemicals.', '色彩丰富的蔬菜含有许多植物化学物。'],
          ['polyphenol', '/ˌpɑːliˈfiːnɔːl/', '多酚', 'Green tea is rich in polyphenols.', '绿茶富含多酚。'],
          ['flavonoid', '/ˈfleɪvənɔɪd/', '类黄酮', 'Dark chocolate contains a flavonoid that may benefit the heart.', '黑巧克力含有一种可能对心脏有益的类黄酮。'],
          ['carotenoid', '/kəˈrɑːtənɔɪd/', '类胡萝卜素', 'Carotenoids give carrots their orange color.', '类胡萝卜素使胡萝卜呈现橙色。'],
          ['lycopene', '/ˈlaɪkəpiːn/', '番茄红素', 'Tomatoes are rich in lycopene.', '番茄富含番茄红素。'],
          ['anthocyanin', '/ˌænθəˈsaɪənɪn/', '花青素', 'Anthocyanin gives blueberries their blue color.', '花青素使蓝莓呈现蓝色。'],
          ['probiotic', '/ˌproʊbaɪˈɑːtɪk/', '益生菌', 'Yogurt contains probiotic bacteria.', '酸奶含有益生菌。'],
          ['prebiotic', '/ˌpriːbaɪˈɑːtɪk/', '益生元', 'Onions and garlic contain prebiotic fiber.', '洋葱和大蒜含有益生元纤维。'],
          ['antinutrient', '/ˌæntiˈnuːtriənt/', '抗营养因子', 'Phytate is an antinutrient that can reduce iron absorption.', '植酸是一种会降低铁吸收的抗营养因子。'],
          ['food additive', '/fuːd ˈædətɪv/', '食品添加剂', 'A food additive is used to improve taste, color or shelf life.', '食品添加剂用于改善味道、颜色或延长保质期。'],
          ['preservative', '/prɪˈzɜːrvətɪv/', '防腐剂', 'Salt has been used as a preservative for centuries.', '盐作为防腐剂已被使用了几个世纪。'],
          ['sweetener', '/ˈswiːtnər/', '甜味剂', 'Many diet drinks use an artificial sweetener.', '许多无糖饮料使用人工甜味剂。'],
          ['added sugar', '/ˈædɪd ˈʃʊɡər/', '添加糖', 'Limit added sugar to less than 10 percent of daily calories.', '把添加糖限制在每日热量的10%以下。'],
          ['emulsifier', '/ɪˈmʌlsɪfaɪər/', '乳化剂', 'Egg yolk acts as an emulsifier in mayonnaise.', '蛋黄在蛋黄酱中充当乳化剂。'],
        ],
      },
      {
        name: '标签与膳食指南',
        words: [
          ['food label', '/fuːd ˈleɪbəl/', '食品标签', 'Always read the food label before you buy.', '购买前一定要阅读食品标签。'],
          ['nutrition facts', '/nuˈtrɪʃən fækts/', '营养成分表', 'The nutrition facts panel shows calories and nutrients.', '营养成分表显示热量和营养素含量。'],
          ['serving size', '/ˈsɜːrvɪŋ saɪz/', '每份分量', 'The serving size on this package is one cup.', '这个包装上标注的每份分量是一杯。'],
          ['daily value', '/ˈdeɪli ˈvæljuː/', '每日营养素参考值（%DV）', 'This cereal provides 20 percent of the daily value for iron.', '这种麦片提供了铁每日参考值的20%。'],
          ['ingredient list', '/ɪnˈɡriːdiənt lɪst/', '配料表', 'The ingredient list is ordered by weight.', '配料表按重量从多到少排列。'],
          ['Recommended Dietary Allowance', '/ˌrekəˈmendɪd ˈdaɪəteri əˈlaʊəns/', '推荐膳食营养素供给量（RDA）', 'The Recommended Dietary Allowance for vitamin C is about 75 to 90 milligrams.', '维生素C的推荐膳食供给量约为75至90毫克。'],
          ['Dietary Reference Intakes', '/ˈdaɪəteri ˈrefərəns ˈɪnteɪks/', '膳食营养素参考摄入量（DRIs）', 'The Dietary Reference Intakes are used to plan healthy diets.', '膳食营养素参考摄入量用于规划健康饮食。'],
          ['Tolerable Upper Intake Level', '/ˈtɑːlərəbəl ˈʌpər ˈɪnteɪk ˈlevəl/', '可耐受最高摄入量（UL）', 'Do not exceed the Tolerable Upper Intake Level for vitamin A.', '不要超过维生素A的可耐受最高摄入量。'],
          ['dietary guidelines', '/ˈdaɪəteri ˈɡaɪdlaɪnz/', '膳食指南', 'The dietary guidelines recommend eating more whole grains.', '膳食指南建议多吃全谷物。'],
          ['balanced diet', '/ˈbælənst ˈdaɪət/', '均衡饮食', 'A balanced diet contains all the food groups.', '均衡饮食包含所有食物类别。'],
          ['portion', '/ˈpɔːrʃən/', '份量；一份', 'Restaurant portions are often too large.', '餐厅的份量往往太大。'],
          ['nutrient density', '/ˈnuːtriənt ˈdensəti/', '营养密度', 'Spinach has a high nutrient density.', '菠菜的营养密度很高。'],
          ['energy density', '/ˈenərdʒi ˈdensəti/', '能量密度', 'Fried foods have a high energy density.', '油炸食品的能量密度很高。'],
          ['empty calories', '/ˈempti ˈkæləriz/', '空热量（只有热量没有营养）', 'Soda provides empty calories.', '汽水只提供空热量。'],
          ['fortified', '/ˈfɔːrtɪfaɪd/', '强化的（额外添加营养素）', 'This milk is fortified with vitamin D.', '这种牛奶强化添加了维生素D。'],
          ['enriched', '/ɪnˈrɪtʃt/', '营养强化的（补回加工损失）', 'Enriched flour has some B vitamins added back.', '营养强化面粉补回了一些B族维生素。'],
          ['organic', '/ɔːrˈɡænɪk/', '有机的', 'Organic vegetables are grown without synthetic pesticides.', '有机蔬菜在种植时不使用合成农药。'],
          ['moderation', '/ˌmɑːdəˈreɪʃən/', '适量；适度', 'You can enjoy sweets in moderation.', '你可以适量享用甜食。'],
        ],
      },
      {
        name: '食品安全与加工',
        words: [
          ['food safety', '/fuːd ˈseɪfti/', '食品安全', 'Washing your hands is basic food safety.', '洗手是基本的食品安全措施。'],
          ['contamination', '/kənˌtæmɪˈneɪʃən/', '污染', 'Contamination can happen during food storage.', '食物在储存过程中可能受到污染。'],
          ['cross-contamination', '/ˌkrɔːs kənˌtæmɪˈneɪʃən/', '交叉污染', 'Use separate cutting boards to avoid cross-contamination.', '使用不同的砧板以避免交叉污染。'],
          ['pathogen', '/ˈpæθədʒən/', '病原体', 'Salmonella is a common foodborne pathogen.', '沙门氏菌是一种常见的食源性病原体。'],
          ['foodborne illness', '/ˈfuːdbɔːrn ˈɪlnəs/', '食源性疾病', 'Undercooked chicken can cause foodborne illness.', '未煮熟的鸡肉会引起食源性疾病。'],
          ['food allergy', '/fuːd ˈælərdʒi/', '食物过敏', 'A peanut food allergy can be life-threatening.', '花生过敏可能危及生命。'],
          ['allergen', '/ˈælərdʒən/', '过敏原', 'Milk is a common allergen.', '牛奶是一种常见的过敏原。'],
          ['lactose intolerance', '/ˈlæktoʊs ɪnˈtɑːlərəns/', '乳糖不耐受', 'Lactose intolerance is very common in East Asia.', '乳糖不耐受在东亚非常普遍。'],
          ['pasteurization', '/ˌpæstʃərəˈzeɪʃən/', '巴氏杀菌', 'Pasteurization kills harmful bacteria in milk.', '巴氏杀菌能杀死牛奶中的有害细菌。'],
          ['fermentation', '/ˌfɜːrmenˈteɪʃən/', '发酵', 'Fermentation turns milk into yogurt.', '发酵把牛奶变成酸奶。'],
          ['refrigeration', '/rɪˌfrɪdʒəˈreɪʃən/', '冷藏', 'Refrigeration slows the growth of bacteria.', '冷藏能减缓细菌的生长。'],
          ['shelf life', '/ʃelf laɪf/', '保质期', 'Canned food has a long shelf life.', '罐头食品的保质期很长。'],
          ['expiration date', '/ˌekspəˈreɪʃən deɪt/', '到期日；截止日期', 'Check the expiration date on the milk carton.', '检查一下牛奶盒上的到期日。'],
          ['blanching', '/ˈblæntʃɪŋ/', '焯水；热烫', 'Blanching vegetables before freezing keeps their color.', '冷冻前焯水能保持蔬菜的颜色。'],
        ],
      },
      {
        name: '膳食与健康',
        words: [
          ['malnutrition', '/ˌmælnuˈtrɪʃən/', '营养不良', 'Malnutrition includes both undernutrition and obesity.', '营养不良既包括营养不足也包括肥胖。'],
          ['undernutrition', '/ˌʌndərnuˈtrɪʃən/', '营养不足', 'Undernutrition can stunt children\'s growth.', '营养不足会阻碍儿童的生长发育。'],
          ['overweight', '/ˌoʊvərˈweɪt/', '超重的', 'Being overweight increases the risk of diabetes.', '超重会增加患糖尿病的风险。'],
          ['obesity', '/oʊˈbiːsəti/', '肥胖', 'Obesity is a major public health problem.', '肥胖是一个重大的公共卫生问题。'],
          ['body mass index', '/ˈbɑːdi mæs ˈɪndeks/', '体重指数（BMI）', 'Body mass index is weight divided by height squared.', '体重指数等于体重除以身高的平方。'],
          ['hypertension', '/ˌhaɪpərˈtenʃən/', '高血压', 'Eating less salt can help control hypertension.', '少吃盐有助于控制高血压。'],
          ['diabetes', '/ˌdaɪəˈbiːtiːz/', '糖尿病', 'Type 2 diabetes is linked to diet and lifestyle.', '2型糖尿病与饮食和生活方式有关。'],
          ['cardiovascular disease', '/ˌkɑːrdioʊˈvæskjələr dɪˈziːz/', '心血管疾病', 'Cardiovascular disease is the leading cause of death worldwide.', '心血管疾病是全球首要死因。'],
          ['anemia', '/əˈniːmiə/', '贫血', 'Iron deficiency is the most common cause of anemia.', '缺铁是贫血最常见的原因。'],
          ['osteoporosis', '/ˌɑːstioʊpəˈroʊsɪs/', '骨质疏松', 'Osteoporosis makes bones weak and easy to break.', '骨质疏松使骨骼变脆、容易骨折。'],
          ['chronic disease', '/ˈkrɑːnɪk dɪˈziːz/', '慢性病', 'A healthy diet lowers the risk of chronic disease.', '健康饮食能降低慢性病风险。'],
          ['vegetarian', '/ˌvedʒəˈteriən/', '素食者；素食的', 'A vegetarian does not eat meat.', '素食者不吃肉。'],
          ['vegan', '/ˈviːɡən/', '纯素食者；纯素的', 'A vegan avoids all animal products.', '纯素食者不吃任何动物性产品。'],
          ['Mediterranean diet', '/ˌmedɪtəˈreɪniən ˈdaɪət/', '地中海饮食', 'The Mediterranean diet is rich in olive oil, fish and vegetables.', '地中海饮食富含橄榄油、鱼和蔬菜。'],
          ['satiety', '/səˈtaɪəti/', '饱腹感', 'Protein and fiber increase satiety.', '蛋白质和纤维能增加饱腹感。'],
          ['appetite', '/ˈæpɪtaɪt/', '食欲；胃口', 'Exercise can affect your appetite.', '运动会影响你的食欲。'],
        ],
      },
    ],
  },
  {
    id: 'sports',
    name: '运动营养学',
    icon: '🏃',
    desc: '能量系统、训练、补剂与补水',
    groups: [
      {
        name: '能量系统与代谢',
        words: [
          ['aerobic', '/eˈroʊbɪk/', '有氧的', 'Jogging is an aerobic exercise.', '慢跑是一种有氧运动。'],
          ['anaerobic', '/ˌæneˈroʊbɪk/', '无氧的', 'Sprinting relies mainly on anaerobic energy.', '短跑主要依靠无氧供能。'],
          ['phosphocreatine', '/ˌfɑːsfoʊˈkriːətiːn/', '磷酸肌酸', 'Phosphocreatine supplies energy for the first few seconds of a sprint.', '磷酸肌酸为冲刺的最初几秒提供能量。'],
          ['lactate', '/ˈlækteɪt/', '乳酸（盐）', 'Lactate builds up during intense exercise.', '剧烈运动时乳酸会堆积。'],
          ['lactate threshold', '/ˈlækteɪt ˈθreʃhoʊld/', '乳酸阈', 'Training can raise your lactate threshold.', '训练可以提高你的乳酸阈。'],
          ['VO2 max', '/ˌviː oʊ ˈtuː mæks/', '最大摄氧量', 'Elite runners have a very high VO2 max.', '精英跑者的最大摄氧量非常高。'],
          ['endurance', '/ɪnˈdʊrəns/', '耐力', 'Marathon running requires great endurance.', '马拉松需要极好的耐力。'],
          ['heart rate', '/hɑːrt reɪt/', '心率', 'Your heart rate increases during exercise.', '运动时你的心率会加快。'],
          ['basal metabolic rate', '/ˈbeɪsəl ˌmetəˈbɑːlɪk reɪt/', '基础代谢率（BMR）', 'Muscle mass raises your basal metabolic rate.', '肌肉量会提高你的基础代谢率。'],
          ['resting metabolic rate', '/ˈrestɪŋ ˌmetəˈbɑːlɪk reɪt/', '静息代谢率（RMR）', 'Resting metabolic rate is the energy you burn at rest.', '静息代谢率是你在休息时消耗的能量。'],
          ['energy expenditure', '/ˈenərdʒi ɪkˈspendɪtʃər/', '能量消耗', 'Running increases energy expenditure.', '跑步会增加能量消耗。'],
          ['total daily energy expenditure', '/ˈtoʊtəl ˈdeɪli ˈenərdʒi ɪkˈspendɪtʃər/', '每日总能量消耗（TDEE）', 'Athletes have a high total daily energy expenditure.', '运动员的每日总能量消耗很高。'],
          ['thermic effect of food', '/ˈθɜːrmɪk ɪˈfekt əv fuːd/', '食物热效应（TEF）', 'Protein has the highest thermic effect of food.', '蛋白质的食物热效应最高。'],
          ['energy balance', '/ˈenərdʒi ˈbæləns/', '能量平衡', 'Weight stays stable when you are in energy balance.', '处于能量平衡时体重保持稳定。'],
          ['caloric deficit', '/kəˈlɔːrɪk ˈdefɪsɪt/', '热量缺口', 'You need a caloric deficit to lose fat.', '减脂需要制造热量缺口。'],
          ['caloric surplus', '/kəˈlɔːrɪk ˈsɜːrpləs/', '热量盈余', 'A small caloric surplus helps build muscle.', '少量的热量盈余有助于增肌。'],
          ['fatigue', '/fəˈtiːɡ/', '疲劳', 'Low glycogen levels cause fatigue.', '糖原水平低会导致疲劳。'],
        ],
      },
      {
        name: '训练与身体成分',
        words: [
          ['body composition', '/ˈbɑːdi ˌkɑːmpəˈzɪʃən/', '身体成分', 'Body composition describes how much fat and muscle you have.', '身体成分描述了你有多少脂肪和肌肉。'],
          ['lean body mass', '/liːn ˈbɑːdi mæs/', '瘦体重（去脂体重）', 'Strength training increases lean body mass.', '力量训练会增加瘦体重。'],
          ['body fat percentage', '/ˈbɑːdi fæt pərˈsentɪdʒ/', '体脂率', 'Her body fat percentage dropped after three months of training.', '经过三个月训练，她的体脂率下降了。'],
          ['hypertrophy', '/haɪˈpɜːrtrəfi/', '（肌肉）肥大；增粗', 'Muscle hypertrophy requires training and enough protein.', '肌肉肥大需要训练和足够的蛋白质。'],
          ['resistance training', '/rɪˈzɪstəns ˈtreɪnɪŋ/', '抗阻训练', 'Resistance training makes muscles stronger.', '抗阻训练使肌肉更强壮。'],
          ['strength', '/streŋθ/', '力量', 'Squats build leg strength.', '深蹲能增强腿部力量。'],
          ['muscle protein synthesis', '/ˈmʌsəl ˈproʊtiːn ˈsɪnθəsɪs/', '肌肉蛋白质合成（MPS）', 'Eating protein after exercise boosts muscle protein synthesis.', '运动后摄入蛋白质能促进肌肉蛋白质合成。'],
          ['recovery', '/rɪˈkʌvəri/', '恢复', 'Sleep is essential for recovery.', '睡眠对恢复至关重要。'],
          ['overtraining', '/ˌoʊvərˈtreɪnɪŋ/', '过度训练', 'Overtraining can lead to injury and poor performance.', '过度训练会导致受伤和表现下降。'],
          ['intensity', '/ɪnˈtensəti/', '强度', 'High intensity exercise burns mostly carbohydrates.', '高强度运动主要消耗碳水化合物。'],
          ['high-intensity interval training', '/ˌhaɪ ɪnˈtensəti ˈɪntərvəl ˈtreɪnɪŋ/', '高强度间歇训练（HIIT）', 'High-intensity interval training alternates hard and easy periods.', '高强度间歇训练交替进行高强度和低强度阶段。'],
          ['warm-up', '/ˈwɔːrm ʌp/', '热身', 'A good warm-up reduces the risk of injury.', '充分的热身能降低受伤风险。'],
          ['muscle soreness', '/ˈmʌsəl ˈsɔːrnəs/', '肌肉酸痛', 'Muscle soreness often peaks two days after exercise.', '肌肉酸痛通常在运动后两天达到高峰。'],
          ['sarcopenia', '/ˌsɑːrkəˈpiːniə/', '肌少症', 'Sarcopenia is the loss of muscle with aging.', '肌少症是随年龄增长出现的肌肉流失。'],
          ['low energy availability', '/loʊ ˈenərdʒi əˌveɪləˈbɪləti/', '低能量可用性', 'Low energy availability can harm bone health in athletes.', '低能量可用性会损害运动员的骨骼健康。'],
        ],
      },
      {
        name: '运动补剂',
        words: [
          ['dietary supplement', '/ˈdaɪəteri ˈsʌplɪmənt/', '膳食补充剂', 'A dietary supplement cannot replace a healthy diet.', '膳食补充剂不能替代健康的饮食。'],
          ['ergogenic aid', '/ˌɜːrɡoʊˈdʒenɪk eɪd/', '运动增力剂（提高运动表现的手段）', 'Caffeine is a well-known ergogenic aid.', '咖啡因是一种著名的运动增力剂。'],
          ['creatine', '/ˈkriːətiːn/', '肌酸', 'Creatine can improve short bursts of power.', '肌酸能提高短时爆发力。'],
          ['caffeine', '/kæˈfiːn/', '咖啡因', 'Caffeine can reduce the feeling of fatigue.', '咖啡因可以减轻疲劳感。'],
          ['whey protein', '/weɪ ˈproʊtiːn/', '乳清蛋白', 'Whey protein is digested quickly.', '乳清蛋白消化得很快。'],
          ['casein', '/ˈkeɪsiːn/', '酪蛋白', 'Casein is digested slowly, so some athletes take it before bed.', '酪蛋白消化较慢，所以有些运动员睡前服用。'],
          ['branched-chain amino acids', '/bræntʃt tʃeɪn əˈmiːnoʊ ˈæsɪdz/', '支链氨基酸（BCAA）', 'Leucine is one of the branched-chain amino acids.', '亮氨酸是支链氨基酸之一。'],
          ['beta-alanine', '/ˌbeɪtə ˈæləniːn/', 'β-丙氨酸', 'Beta-alanine may cause a tingling feeling in the skin.', 'β-丙氨酸可能会引起皮肤刺痒感。'],
          ['nitrate', '/ˈnaɪtreɪt/', '硝酸盐', 'Beetroot juice is high in nitrate.', '甜菜根汁富含硝酸盐。'],
          ['multivitamin', '/ˌmʌltiˈvaɪtəmɪn/', '复合维生素', 'A multivitamin may help if your diet is limited.', '如果饮食受限，复合维生素可能有帮助。'],
          ['dosage', '/ˈdoʊsɪdʒ/', '剂量', 'Always follow the recommended dosage.', '务必遵循推荐剂量。'],
          ['placebo', '/pləˈsiːboʊ/', '安慰剂', 'Some supplements work no better than a placebo.', '有些补剂的效果并不比安慰剂好。'],
          ['doping', '/ˈdoʊpɪŋ/', '使用兴奋剂', 'Doping is banned in competitive sports.', '竞技体育禁止使用兴奋剂。'],
        ],
      },
      {
        name: '补水与营养时机',
        words: [
          ['hydration', '/haɪˈdreɪʃən/', '水合；补水', 'Good hydration improves performance.', '充足的补水能提高运动表现。'],
          ['dehydration', '/ˌdiːhaɪˈdreɪʃən/', '脱水', 'Dehydration can cause headaches and dizziness.', '脱水会导致头痛和头晕。'],
          ['sweat rate', '/swet reɪt/', '出汗率', 'Weigh yourself before and after exercise to estimate your sweat rate.', '运动前后称体重可以估算你的出汗率。'],
          ['sports drink', '/spɔːrts drɪŋk/', '运动饮料', 'A sports drink provides fluid, sugar and electrolytes.', '运动饮料提供水分、糖和电解质。'],
          ['hyponatremia', '/ˌhaɪpoʊnəˈtriːmiə/', '低钠血症', 'Drinking too much plain water can cause hyponatremia.', '饮用过多的白开水可能导致低钠血症。'],
          ['carbohydrate loading', '/ˌkɑːrboʊˈhaɪdreɪt ˈloʊdɪŋ/', '碳水加载（糖原负荷法）', 'Marathon runners use carbohydrate loading before a race.', '马拉松跑者在比赛前进行碳水加载。'],
          ['glycogen depletion', '/ˈɡlaɪkədʒən dɪˈpliːʃən/', '糖原耗竭', 'Glycogen depletion makes you slow down suddenly.', '糖原耗竭会让你突然慢下来。'],
          ['hitting the wall', '/ˈhɪtɪŋ ðə wɔːl/', '撞墙（耐力运动中能量耗尽）', 'Many marathon runners experience hitting the wall at around 30 kilometers.', '许多马拉松跑者在30公里左右会“撞墙”。'],
          ['refueling', '/riːˈfjuːəlɪŋ/', '补充能量', 'Refueling with carbs and protein speeds up recovery.', '用碳水和蛋白质补充能量能加快恢复。'],
          ['pre-workout meal', '/ˌpriː ˈwɜːrkaʊt miːl/', '训练前餐', 'Eat a pre-workout meal two to three hours before training.', '在训练前两到三小时吃训练前餐。'],
          ['post-workout', '/ˌpoʊst ˈwɜːrkaʊt/', '训练后的', 'A post-workout snack should contain protein.', '训练后的加餐应该含有蛋白质。'],
          ['nutrient timing', '/ˈnuːtriənt ˈtaɪmɪŋ/', '营养时机', 'Nutrient timing means eating the right food at the right time.', '营养时机是指在合适的时间吃合适的食物。'],
          ['muscle cramp', '/ˈmʌsəl kræmp/', '肌肉痉挛；抽筋', 'He got a muscle cramp in his calf during the game.', '他在比赛中小腿抽筋了。'],
          ['heat stroke', '/hiːt stroʊk/', '中暑（热射病）', 'Heat stroke is a medical emergency.', '中暑（热射病）是一种医疗急症。'],
        ],
      },
    ],
  },
];
