VOCAB.push({
  id: 'biochem',
  name: '人体生化营养学',
  icon: '🧬',
  desc: '营养素、代谢途径、维生素矿物质（RD 考试领域 I：营养原理）',
  groups: [
    {
      name: '营养学基础概念',
      tip: '最常用的总称词，先打好基础。macro- 大，micro- 小；ana- 向上（合成），cata- 向下（分解）。',
      words: [
        ['nutrition', '/nuˈtrɪʃən/', '营养；营养学', 'Good nutrition is the foundation of good health.', '良好的营养是健康的基础。'],
        ['nutrient', '/ˈnuːtriənt/', '营养素', 'Vegetables provide many important nutrients.', '蔬菜提供许多重要的营养素。'],
        ['macronutrient', '/ˌmækroʊˈnuːtriənt/', '宏量营养素', 'Carbohydrates, proteins and fats are the three main macronutrients.', '碳水化合物、蛋白质和脂肪是三大宏量营养素。'],
        ['micronutrient', '/ˌmaɪkroʊˈnuːtriənt/', '微量营养素', 'Vitamins and minerals are called micronutrients because we need them in small amounts.', '维生素和矿物质被称为微量营养素，因为我们只需要少量。'],
        ['essential nutrient', '/ɪˈsenʃəl ˈnuːtriənt/', '必需营养素', 'An essential nutrient must come from food because the body cannot make enough of it.', '必需营养素必须从食物中获取，因为身体无法合成足够的量。'],
        ['conditionally essential', '/kənˈdɪʃənəli ɪˈsenʃəl/', '条件必需的', 'Glutamine may become conditionally essential during severe illness.', '在严重疾病期间，谷氨酰胺可能变成条件必需的。'],
        ['calorie', '/ˈkæləri/', '卡路里；热量', 'One gram of fat provides nine calories.', '一克脂肪提供九卡路里热量。'],
        ['kilocalorie', '/ˈkɪloʊˌkæləri/', '千卡', 'Food energy is usually measured in kilocalories.', '食物能量通常以千卡为单位计量。'],
        ['kilojoule', '/ˈkɪloʊˌdʒuːl/', '千焦', 'One kilocalorie equals about 4.18 kilojoules.', '1千卡约等于4.18千焦。'],
        ['energy', '/ˈenərdʒi/', '能量', 'The body gets energy from carbohydrates, fats and proteins.', '身体从碳水化合物、脂肪和蛋白质中获取能量。'],
        ['metabolism', '/məˈtæbəlɪzəm/', '新陈代谢', 'Metabolism includes all the chemical reactions in the body.', '新陈代谢包括体内所有的化学反应。'],
        ['anabolism', '/əˈnæbəlɪzəm/', '合成代谢', 'Anabolism builds large molecules such as proteins from small ones.', '合成代谢把小分子构建成蛋白质等大分子。'],
        ['catabolism', '/kəˈtæbəlɪzəm/', '分解代谢', 'Catabolism breaks down molecules to release energy.', '分解代谢分解分子以释放能量。'],
        ['metabolite', '/məˈtæbəlaɪt/', '代谢物', 'Lactate is a metabolite of glucose.', '乳酸是葡萄糖的一种代谢物。'],
        ['diet', '/ˈdaɪət/', '饮食；膳食', 'A healthy diet includes a variety of foods.', '健康的饮食包含多种多样的食物。'],
        ['deficiency', '/dɪˈfɪʃənsi/', '缺乏（症）', 'Iron deficiency can make you feel tired.', '缺铁会让你感到疲倦。'],
        ['toxicity', '/tɑːkˈsɪsəti/', '毒性；中毒', 'Vitamin A toxicity can damage the liver.', '维生素A中毒会损伤肝脏。'],
        ['intake', '/ˈɪnteɪk/', '摄入量', 'Try to reduce your daily salt intake.', '尽量减少每日的盐摄入量。'],
        ['digestion', '/daɪˈdʒestʃən/', '消化', 'Digestion begins in the mouth.', '消化从口腔开始。'],
        ['absorption', '/əbˈzɔːrpʃən/', '吸收', 'Most nutrient absorption happens in the small intestine.', '大部分营养素的吸收发生在小肠。'],
        ['bioavailability', '/ˌbaɪoʊəˌveɪləˈbɪləti/', '生物利用度', 'The bioavailability of iron from meat is higher than from plants.', '肉类中铁的生物利用度高于植物。'],
        ['homeostasis', '/ˌhoʊmioʊˈsteɪsɪs/', '体内平衡；稳态', 'The body maintains homeostasis by keeping blood sugar stable.', '身体通过保持血糖稳定来维持稳态。'],
        ['molecule', '/ˈmɑːlɪkjuːl/', '分子', 'A glucose molecule contains six carbon atoms.', '一个葡萄糖分子含有六个碳原子。'],
        ['compound', '/ˈkɑːmpaʊnd/', '化合物', 'Water is a compound of hydrogen and oxygen.', '水是由氢和氧组成的化合物。'],
        ['substrate', '/ˈsʌbstreɪt/', '底物', 'Lactose is the substrate for the enzyme lactase.', '乳糖是乳糖酶的底物。'],
        ['catalyst', '/ˈkætəlɪst/', '催化剂', 'An enzyme acts as a biological catalyst.', '酶是一种生物催化剂。'],
      ],
    },
    {
      name: '单糖与双糖（-ose 糖）',
      tip: '以 -ose 结尾的词几乎都是“糖”：glucose 葡萄糖、fructose 果糖、lactose 乳糖……mono- 单，di- 双；-itol 结尾是糖醇。',
      words: [
        ['carbohydrate', '/ˌkɑːrboʊˈhaɪdreɪt/', '碳水化合物', 'Rice and bread are rich in carbohydrates.', '米饭和面包富含碳水化合物。'],
        ['sugar', '/ˈʃʊɡər/', '糖', 'Soft drinks contain a lot of sugar.', '软饮料含有大量的糖。'],
        ['monosaccharide', '/ˌmɑːnoʊˈsækəraɪd/', '单糖', 'Glucose is a monosaccharide, the simplest form of sugar.', '葡萄糖是一种单糖，是糖最简单的形式。'],
        ['disaccharide', '/daɪˈsækəraɪd/', '双糖', 'Sucrose is a disaccharide made of two sugar units.', '蔗糖是由两个糖单位组成的双糖。'],
        ['glucose', '/ˈɡluːkoʊs/', '葡萄糖', 'Glucose is the main fuel for the brain.', '葡萄糖是大脑的主要燃料。'],
        ['dextrose', '/ˈdekstroʊs/', '右旋糖（即葡萄糖）', 'Intravenous fluids often contain dextrose.', '静脉输液中常含有右旋糖。'],
        ['fructose', '/ˈfrʌktoʊs/', '果糖', 'Fructose is the natural sugar found in fruit.', '果糖是水果中天然存在的糖。'],
        ['galactose', '/ɡəˈlæktoʊs/', '半乳糖', 'Lactose is made of glucose and galactose.', '乳糖由葡萄糖和半乳糖组成。'],
        ['ribose', '/ˈraɪboʊs/', '核糖', 'Ribose is part of the structure of RNA and ATP.', '核糖是RNA和ATP结构的一部分。'],
        ['sucrose', '/ˈsuːkroʊs/', '蔗糖', 'Table sugar is sucrose.', '餐桌上的白糖就是蔗糖。'],
        ['lactose', '/ˈlæktoʊs/', '乳糖', 'Milk contains a sugar called lactose.', '牛奶含有一种叫乳糖的糖。'],
        ['maltose', '/ˈmɔːltoʊs/', '麦芽糖', 'Maltose is produced when starch is broken down.', '淀粉分解时会产生麦芽糖。'],
        ['high-fructose corn syrup', '/ˌhaɪ ˈfrʌktoʊs kɔːrn ˈsɪrəp/', '高果糖玉米糖浆', 'Many soft drinks are sweetened with high-fructose corn syrup.', '许多软饮料用高果糖玉米糖浆增甜。'],
        ['sugar alcohol', '/ˈʃʊɡər ˈælkəhɔːl/', '糖醇', 'A sugar alcohol provides fewer calories than sugar.', '糖醇提供的热量比糖少。'],
        ['sorbitol', '/ˈsɔːrbɪtɔːl/', '山梨醇', 'Too much sorbitol can cause diarrhea.', '摄入过多山梨醇会引起腹泻。'],
        ['xylitol', '/ˈzaɪlɪtɔːl/', '木糖醇', 'Chewing gum with xylitol may help prevent cavities.', '含木糖醇的口香糖可能有助于预防蛀牙。'],
      ],
    },
    {
      name: '多糖与膳食纤维（poly- 多）',
      tip: 'poly- 多，oligo- 少（寡）；amylo- 与淀粉有关；fiber 纤维分为 soluble 可溶性 和 insoluble 不溶性。',
      words: [
        ['polysaccharide', '/ˌpɑːliˈsækəraɪd/', '多糖', 'Starch is a polysaccharide made of many glucose units.', '淀粉是由许多葡萄糖单位组成的多糖。'],
        ['oligosaccharide', '/ˌɑːlɪɡoʊˈsækəraɪd/', '寡糖', 'Beans contain oligosaccharides that can cause gas.', '豆类含有会引起胀气的寡糖。'],
        ['starch', '/stɑːrtʃ/', '淀粉', 'Potatoes are a good source of starch.', '土豆是淀粉的良好来源。'],
        ['amylose', '/ˈæmɪloʊs/', '直链淀粉', 'Amylose is a straight chain of glucose units.', '直链淀粉是由葡萄糖单位组成的直链。'],
        ['amylopectin', '/ˌæmɪloʊˈpektɪn/', '支链淀粉', 'Sticky rice is rich in amylopectin.', '糯米富含支链淀粉。'],
        ['resistant starch', '/rɪˈzɪstənt stɑːrtʃ/', '抗性淀粉', 'Cooled potatoes contain more resistant starch.', '放凉的土豆含有更多抗性淀粉。'],
        ['glycogen', '/ˈɡlaɪkədʒən/', '糖原', 'The liver and muscles store glucose as glycogen.', '肝脏和肌肉以糖原的形式储存葡萄糖。'],
        ['dietary fiber', '/ˈdaɪəteri ˈfaɪbər/', '膳食纤维', 'Dietary fiber helps keep your digestive system healthy.', '膳食纤维有助于保持消化系统健康。'],
        ['soluble fiber', '/ˈsɑːljəbəl ˈfaɪbər/', '可溶性纤维', 'Oats contain soluble fiber that can lower cholesterol.', '燕麦含有能降低胆固醇的可溶性纤维。'],
        ['insoluble fiber', '/ɪnˈsɑːljəbəl ˈfaɪbər/', '不溶性纤维', 'Insoluble fiber adds bulk to stool and prevents constipation.', '不溶性纤维增加粪便体积、预防便秘。'],
        ['viscous fiber', '/ˈvɪskəs ˈfaɪbər/', '黏性纤维', 'Viscous fiber forms a gel and slows digestion.', '黏性纤维形成凝胶并减缓消化。'],
        ['cellulose', '/ˈseljəloʊs/', '纤维素', 'Humans cannot digest cellulose.', '人类无法消化纤维素。'],
        ['hemicellulose', '/ˌhemiˈseljəloʊs/', '半纤维素', 'Whole grains contain hemicellulose.', '全谷物含有半纤维素。'],
        ['pectin', '/ˈpektɪn/', '果胶', 'Apples are rich in pectin.', '苹果富含果胶。'],
        ['beta-glucan', '/ˌbeɪtə ˈɡluːkæn/', 'β-葡聚糖', 'Oat beta-glucan helps lower LDL cholesterol.', '燕麦β-葡聚糖有助于降低低密度脂蛋白胆固醇。'],
        ['inulin', '/ˈɪnjəlɪn/', '菊粉', 'Inulin is a fiber that feeds good gut bacteria.', '菊粉是一种能滋养肠道有益菌的纤维。'],
        ['lignin', '/ˈlɪɡnɪn/', '木质素', 'Lignin is found in the woody parts of plants.', '木质素存在于植物的木质部分。'],
        ['psyllium', '/ˈsɪliəm/', '车前子（壳）', 'Psyllium is often used as a fiber supplement.', '车前子常被用作纤维补充剂。'],
      ],
    },
    {
      name: '血糖调节（gluc- / glyc- 糖）',
      tip: 'gluc- / glyc- 都表示“糖”；hyper- 过高，hypo- 过低；-emia 表示“血液中…的状态”。',
      words: [
        ['blood glucose', '/blʌd ˈɡluːkoʊs/', '血糖', 'Blood glucose rises after a meal.', '饭后血糖会升高。'],
        ['glycemic index', '/ɡlaɪˈsiːmɪk ˈɪndeks/', '血糖生成指数（GI）', 'White bread has a high glycemic index.', '白面包的血糖生成指数很高。'],
        ['glycemic load', '/ɡlaɪˈsiːmɪk loʊd/', '血糖负荷（GL）', 'Glycemic load considers both the type and the amount of carbohydrate.', '血糖负荷同时考虑碳水的种类和数量。'],
        ['hyperglycemia', '/ˌhaɪpərɡlaɪˈsiːmiə/', '高血糖', 'Uncontrolled diabetes leads to hyperglycemia.', '未控制的糖尿病会导致高血糖。'],
        ['hypoglycemia', '/ˌhaɪpoʊɡlaɪˈsiːmiə/', '低血糖', 'Skipping meals while taking insulin can cause hypoglycemia.', '使用胰岛素时不吃饭可能引起低血糖。'],
        ['insulin', '/ˈɪnsəlɪn/', '胰岛素', 'Insulin helps cells take up glucose from the blood.', '胰岛素帮助细胞从血液中摄取葡萄糖。'],
        ['glucagon', '/ˈɡluːkəɡɑːn/', '胰高血糖素', 'Glucagon raises blood sugar when it is too low.', '血糖过低时，胰高血糖素会使其升高。'],
        ['insulin resistance', '/ˈɪnsəlɪn rɪˈzɪstəns/', '胰岛素抵抗', 'Obesity is a major cause of insulin resistance.', '肥胖是胰岛素抵抗的主要原因。'],
        ['insulin sensitivity', '/ˈɪnsəlɪn ˌsensəˈtɪvəti/', '胰岛素敏感性', 'Regular exercise improves insulin sensitivity.', '规律运动能改善胰岛素敏感性。'],
        ['glucose tolerance', '/ˈɡluːkoʊs ˈtɑːlərəns/', '葡萄糖耐量', 'An oral glucose tolerance test is used to diagnose diabetes.', '口服葡萄糖耐量试验用于诊断糖尿病。'],
        ['glucose transporter', '/ˈɡluːkoʊs trænsˈpɔːrtər/', '葡萄糖转运蛋白（GLUT）', 'Insulin moves the glucose transporter to the surface of muscle cells.', '胰岛素把葡萄糖转运蛋白移到肌肉细胞表面。'],
        ['epinephrine', '/ˌepɪˈnefrɪn/', '肾上腺素', 'Epinephrine raises blood glucose during stress.', '在应激状态下肾上腺素会升高血糖。'],
        ['incretin', '/ɪnˈkriːtɪn/', '肠促胰素', 'An incretin hormone increases insulin release after eating.', '肠促胰素会在进食后增加胰岛素释放。'],
      ],
    },
    {
      name: '氨基酸（-ine 结尾）',
      tip: '大部分氨基酸名称以 -ine 结尾：leucine、lysine、valine……九种必需氨基酸口诀：His, Ile, Leu, Lys, Met, Phe, Thr, Trp, Val。',
      words: [
        ['amino acid', '/əˈmiːnoʊ ˈæsɪd/', '氨基酸', 'Proteins are made of amino acids.', '蛋白质由氨基酸组成。'],
        ['essential amino acid', '/ɪˈsenʃəl əˈmiːnoʊ ˈæsɪd/', '必需氨基酸', 'There are nine essential amino acids that we must get from food.', '有九种必需氨基酸必须从食物中获取。'],
        ['nonessential amino acid', '/ˌnɑːnɪˈsenʃəl əˈmiːnoʊ ˈæsɪd/', '非必需氨基酸', 'The body can make a nonessential amino acid by itself.', '身体可以自己合成非必需氨基酸。'],
        ['limiting amino acid', '/ˈlɪmɪtɪŋ əˈmiːnoʊ ˈæsɪd/', '限制性氨基酸', 'Lysine is the limiting amino acid in most grains.', '赖氨酸是大多数谷物中的限制性氨基酸。'],
        ['leucine', '/ˈluːsiːn/', '亮氨酸', 'Leucine plays a key role in building muscle.', '亮氨酸在肌肉构建中起关键作用。'],
        ['isoleucine', '/ˌaɪsoʊˈluːsiːn/', '异亮氨酸', 'Isoleucine is one of the three branched-chain amino acids.', '异亮氨酸是三种支链氨基酸之一。'],
        ['valine', '/ˈveɪliːn/', '缬氨酸', 'Valine is an essential amino acid found in meat and dairy.', '缬氨酸是存在于肉类和乳制品中的必需氨基酸。'],
        ['lysine', '/ˈlaɪsiːn/', '赖氨酸', 'Legumes are a good source of lysine.', '豆类是赖氨酸的良好来源。'],
        ['methionine', '/məˈθaɪəniːn/', '甲硫氨酸（蛋氨酸）', 'Methionine is the limiting amino acid in beans.', '甲硫氨酸是豆类中的限制性氨基酸。'],
        ['phenylalanine', '/ˌfenəlˈæləniːn/', '苯丙氨酸', 'People with PKU must limit phenylalanine.', '苯丙酮尿症患者必须限制苯丙氨酸。'],
        ['threonine', '/ˈθriːəniːn/', '苏氨酸', 'Threonine is needed to make collagen.', '合成胶原蛋白需要苏氨酸。'],
        ['tryptophan', '/ˈtrɪptəfæn/', '色氨酸', 'The body uses tryptophan to make niacin and serotonin.', '身体利用色氨酸合成烟酸和血清素。'],
        ['histidine', '/ˈhɪstɪdiːn/', '组氨酸', 'Histidine is essential for infants.', '组氨酸对婴儿是必需的。'],
        ['arginine', '/ˈɑːrdʒɪniːn/', '精氨酸', 'Arginine may support wound healing.', '精氨酸可能有助于伤口愈合。'],
        ['glutamine', '/ˈɡluːtəmiːn/', '谷氨酰胺', 'Glutamine is an important fuel for gut cells.', '谷氨酰胺是肠道细胞的重要燃料。'],
        ['cysteine', '/ˈsɪstiːn/', '半胱氨酸', 'Cysteine contains sulfur.', '半胱氨酸含有硫。'],
        ['tyrosine', '/ˈtaɪrəsiːn/', '酪氨酸', 'The body makes tyrosine from phenylalanine.', '身体用苯丙氨酸合成酪氨酸。'],
        ['glycine', '/ˈɡlaɪsiːn/', '甘氨酸', 'Glycine is the simplest amino acid.', '甘氨酸是结构最简单的氨基酸。'],
        ['alanine', '/ˈæləniːn/', '丙氨酸', 'Muscles release alanine during fasting.', '禁食时肌肉会释放丙氨酸。'],
        ['taurine', '/ˈtɔːriːn/', '牛磺酸', 'Taurine is added to many energy drinks.', '许多能量饮料中添加了牛磺酸。'],
      ],
    },
    {
      name: '蛋白质结构与质量',
      tip: 'peptide 肽：di- 二、poly- 多；complete / incomplete 完全 / 不完全蛋白质；protein quality 用 biological value、digestibility 衡量。',
      words: [
        ['protein', '/ˈproʊtiːn/', '蛋白质', 'Eggs are an excellent source of protein.', '鸡蛋是蛋白质的极佳来源。'],
        ['peptide', '/ˈpeptaɪd/', '肽', 'A peptide is a short chain of amino acids.', '肽是由氨基酸组成的短链。'],
        ['dipeptide', '/daɪˈpeptaɪd/', '二肽', 'A dipeptide contains two amino acids.', '二肽含有两个氨基酸。'],
        ['polypeptide', '/ˌpɑːliˈpeptaɪd/', '多肽', 'A protein is made of one or more polypeptide chains.', '蛋白质由一条或多条多肽链组成。'],
        ['peptide bond', '/ˈpeptaɪd bɑːnd/', '肽键', 'A peptide bond links two amino acids together.', '肽键把两个氨基酸连接在一起。'],
        ['enzyme', '/ˈenzaɪm/', '酶', 'Enzymes speed up chemical reactions in the body.', '酶能加快体内的化学反应。'],
        ['complete protein', '/kəmˈpliːt ˈproʊtiːn/', '完全蛋白质', 'Soy is a complete protein that contains all essential amino acids.', '大豆是含有全部必需氨基酸的完全蛋白质。'],
        ['incomplete protein', '/ˌɪnkəmˈpliːt ˈproʊtiːn/', '不完全蛋白质', 'Most plant foods provide incomplete protein.', '大多数植物性食物提供的是不完全蛋白质。'],
        ['complementary proteins', '/ˌkɑːmplɪˈmentəri ˈproʊtiːnz/', '互补蛋白质（蛋白质互补）', 'Rice and beans are complementary proteins.', '米饭和豆子是互补蛋白质。'],
        ['protein quality', '/ˈproʊtiːn ˈkwɑːləti/', '蛋白质质量', 'Protein quality depends on amino acid content and digestibility.', '蛋白质质量取决于氨基酸含量和消化率。'],
        ['biological value', '/ˌbaɪəˈlɑːdʒɪkəl ˈvæljuː/', '生物价（BV）', 'Egg protein has a very high biological value.', '鸡蛋蛋白的生物价非常高。'],
        ['protein digestibility', '/ˈproʊtiːn daɪˌdʒestəˈbɪləti/', '蛋白质消化率', 'Cooking can improve protein digestibility.', '烹饪可以提高蛋白质消化率。'],
        ['nitrogen balance', '/ˈnaɪtrədʒən ˈbæləns/', '氮平衡', 'Growing children are usually in positive nitrogen balance.', '正在生长的儿童通常处于正氮平衡。'],
        ['collagen', '/ˈkɑːlədʒən/', '胶原蛋白', 'Collagen is the most abundant protein in the body.', '胶原蛋白是人体中含量最多的蛋白质。'],
        ['denaturation', '/diːˌneɪtʃəˈreɪʃən/', '（蛋白质）变性', 'Cooking an egg causes denaturation of its proteins.', '煮鸡蛋会导致其中的蛋白质变性。'],
        ['antibody', '/ˈæntiˌbɑːdi/', '抗体', 'An antibody is a protein that helps fight infection.', '抗体是一种帮助抵抗感染的蛋白质。'],
        ['transport protein', '/ˈtrænspɔːrt ˈproʊtiːn/', '转运蛋白', 'Albumin is a transport protein in the blood.', '白蛋白是血液中的一种转运蛋白。'],
        ['urea', '/juˈriːə/', '尿素', 'The liver converts excess nitrogen into urea.', '肝脏把多余的氮转化为尿素。'],
      ],
    },
    {
      name: '脂肪酸（fatty acid / -ic acid）',
      tip: '记住分类：saturated 饱和、mono-/poly-unsaturated 单/多不饱和、trans 反式；omega-3 家族：ALA → EPA → DHA；omega-6：linoleic → arachidonic。',
      words: [
        ['fatty acid', '/ˈfæti ˈæsɪd/', '脂肪酸', 'A fatty acid is a building block of fat.', '脂肪酸是脂肪的组成单位。'],
        ['saturated fat', '/ˈsætʃəreɪtɪd fæt/', '饱和脂肪', 'Butter is high in saturated fat.', '黄油的饱和脂肪含量很高。'],
        ['unsaturated fat', '/ʌnˈsætʃəreɪtɪd fæt/', '不饱和脂肪', 'Olive oil is rich in unsaturated fat.', '橄榄油富含不饱和脂肪。'],
        ['monounsaturated', '/ˌmɑːnoʊʌnˈsætʃəreɪtɪd/', '单不饱和的', 'Nuts contain monounsaturated fats.', '坚果含有单不饱和脂肪。'],
        ['polyunsaturated', '/ˌpɑːliʌnˈsætʃəreɪtɪd/', '多不饱和的', 'Fish oil contains polyunsaturated fats.', '鱼油含有多不饱和脂肪。'],
        ['trans fat', '/trænz fæt/', '反式脂肪', 'Trans fat raises the risk of heart disease.', '反式脂肪会增加心脏病风险。'],
        ['hydrogenation', '/haɪˌdrɑːdʒəˈneɪʃən/', '氢化', 'Partial hydrogenation of oils creates trans fat.', '油脂的部分氢化会产生反式脂肪。'],
        ['essential fatty acid', '/ɪˈsenʃəl ˈfæti ˈæsɪd/', '必需脂肪酸', 'Linoleic acid is an essential fatty acid.', '亚油酸是一种必需脂肪酸。'],
        ['omega-3 fatty acid', '/oʊˈmeɪɡə θriː ˈfæti ˈæsɪd/', 'ω-3脂肪酸', 'Salmon is rich in omega-3 fatty acids.', '三文鱼富含ω-3脂肪酸。'],
        ['omega-6 fatty acid', '/oʊˈmeɪɡə sɪks ˈfæti ˈæsɪd/', 'ω-6脂肪酸', 'Vegetable oils are the main source of omega-6 fatty acids.', '植物油是ω-6脂肪酸的主要来源。'],
        ['linoleic acid', '/ˌlɪnəˈleɪɪk ˈæsɪd/', '亚油酸（ω-6）', 'Corn oil is high in linoleic acid.', '玉米油的亚油酸含量很高。'],
        ['alpha-linolenic acid', '/ˌælfə ˌlɪnəˈlenɪk ˈæsɪd/', 'α-亚麻酸（ALA，ω-3）', 'Flaxseed is a rich source of alpha-linolenic acid.', '亚麻籽是α-亚麻酸的丰富来源。'],
        ['arachidonic acid', '/əˌrækɪˈdɑːnɪk ˈæsɪd/', '花生四烯酸', 'The body makes arachidonic acid from linoleic acid.', '身体用亚油酸合成花生四烯酸。'],
        ['eicosapentaenoic acid', '/aɪˌkoʊsəˌpentəiˈnoʊɪk ˈæsɪd/', '二十碳五烯酸（EPA）', 'Eicosapentaenoic acid helps reduce inflammation.', '二十碳五烯酸有助于减轻炎症。'],
        ['docosahexaenoic acid', '/doʊˌkoʊsəˌheksəiˈnoʊɪk ˈæsɪd/', '二十二碳六烯酸（DHA）', 'Docosahexaenoic acid is important for brain development.', '二十二碳六烯酸对大脑发育很重要。'],
        ['oleic acid', '/oʊˈliːɪk ˈæsɪd/', '油酸', 'Olive oil is mostly oleic acid.', '橄榄油的主要成分是油酸。'],
        ['palmitic acid', '/pælˈmɪtɪk ˈæsɪd/', '棕榈酸', 'Palm oil contains a lot of palmitic acid.', '棕榈油含有大量棕榈酸。'],
        ['stearic acid', '/stiˈærɪk ˈæsɪd/', '硬脂酸', 'Stearic acid is a saturated fat found in cocoa butter.', '硬脂酸是可可脂中的一种饱和脂肪。'],
        ['short-chain fatty acid', '/ˌʃɔːrt tʃeɪn ˈfæti ˈæsɪd/', '短链脂肪酸', 'Gut bacteria turn fiber into short-chain fatty acids.', '肠道细菌把纤维转化为短链脂肪酸。'],
        ['medium-chain triglyceride', '/ˈmiːdiəm tʃeɪn traɪˈɡlɪsəraɪd/', '中链甘油三酯（MCT）', 'A medium-chain triglyceride is absorbed without bile.', '中链甘油三酯不需要胆汁就能被吸收。'],
      ],
    },
    {
      name: '脂类与脂蛋白（lip- 脂）',
      tip: 'lip- 表示“脂”：lipid、lipoprotein、lipase；-ol 结尾常是醇类（cholesterol、glycerol、sterol）；脂蛋白按密度：chylomicron < VLDL < LDL < HDL。',
      words: [
        ['lipid', '/ˈlɪpɪd/', '脂质', 'Fats and oils are types of lipids.', '脂肪和油都是脂质的类型。'],
        ['fat', '/fæt/', '脂肪', 'Avocados contain healthy fat.', '牛油果含有健康的脂肪。'],
        ['triglyceride', '/traɪˈɡlɪsəraɪd/', '甘油三酯', 'Most fat in food and in the body is stored as triglycerides.', '食物和身体中的大部分脂肪以甘油三酯的形式存在。'],
        ['monoglyceride', '/ˌmɑːnoʊˈɡlɪsəraɪd/', '甘油一酯', 'Lipase breaks a triglyceride into a monoglyceride and two fatty acids.', '脂肪酶把甘油三酯分解成一个甘油一酯和两个脂肪酸。'],
        ['glycerol', '/ˈɡlɪsərɔːl/', '甘油', 'A triglyceride contains one glycerol and three fatty acids.', '一个甘油三酯含有一个甘油和三个脂肪酸。'],
        ['cholesterol', '/kəˈlestərɔːl/', '胆固醇', 'Egg yolks contain cholesterol.', '蛋黄含有胆固醇。'],
        ['sterol', '/ˈstɪrɔːl/', '固醇', 'Cholesterol is the best-known sterol.', '胆固醇是最为人熟知的固醇。'],
        ['plant sterol', '/plænt ˈstɪrɔːl/', '植物固醇', 'Plant sterols can block cholesterol absorption.', '植物固醇可以阻止胆固醇的吸收。'],
        ['phospholipid', '/ˌfɑːsfoʊˈlɪpɪd/', '磷脂', 'Cell membranes are made mainly of phospholipids.', '细胞膜主要由磷脂构成。'],
        ['lecithin', '/ˈlesəθɪn/', '卵磷脂', 'Lecithin is used as an emulsifier in chocolate.', '卵磷脂在巧克力中用作乳化剂。'],
        ['micelle', '/maɪˈsel/', '微胶粒（胶束）', 'Bile salts form a micelle that carries fat to the intestinal wall.', '胆盐形成微胶粒，把脂肪运送到肠壁。'],
        ['lipoprotein', '/ˌlɪpoʊˈproʊtiːn/', '脂蛋白', 'A lipoprotein carries fat through the blood.', '脂蛋白在血液中运输脂肪。'],
        ['chylomicron', '/ˌkaɪloʊˈmaɪkrɑːn/', '乳糜微粒', 'A chylomicron carries dietary fat from the intestine.', '乳糜微粒从肠道运送膳食脂肪。'],
        ['very-low-density lipoprotein', '/ˈveri loʊ ˈdensəti ˌlɪpoʊˈproʊtiːn/', '极低密度脂蛋白（VLDL）', 'The liver makes very-low-density lipoprotein to carry triglycerides.', '肝脏合成极低密度脂蛋白来运输甘油三酯。'],
        ['low-density lipoprotein', '/ˌloʊ ˈdensəti ˌlɪpoʊˈproʊtiːn/', '低密度脂蛋白（LDL，“坏”胆固醇）', 'High levels of low-density lipoprotein increase heart disease risk.', '低密度脂蛋白水平过高会增加心脏病风险。'],
        ['high-density lipoprotein', '/ˌhaɪ ˈdensəti ˌlɪpoʊˈproʊtiːn/', '高密度脂蛋白（HDL，“好”胆固醇）', 'High-density lipoprotein helps remove cholesterol from the blood.', '高密度脂蛋白有助于清除血液中的胆固醇。'],
        ['apolipoprotein', '/ˌæpoʊˌlɪpoʊˈproʊtiːn/', '载脂蛋白', 'Each lipoprotein has an apolipoprotein on its surface.', '每种脂蛋白表面都有载脂蛋白。'],
        ['lipoprotein lipase', '/ˌlɪpoʊˈproʊtiːn ˈlaɪpeɪs/', '脂蛋白脂肪酶', 'Lipoprotein lipase releases fatty acids from triglycerides in the blood.', '脂蛋白脂肪酶从血液中的甘油三酯释放脂肪酸。'],
        ['ketone body', '/ˈkiːtoʊn ˈbɑːdi/', '酮体', 'The liver makes ketone bodies when carbohydrate intake is very low.', '当碳水摄入极低时，肝脏会生成酮体。'],
      ],
    },
    {
      name: '脂溶性维生素（A D E K）',
      tip: '口诀“ADEK 溶于脂”：会储存在体内，过量易中毒。-ol / -in 结尾的化学名对应各种维生素。',
      words: [
        ['vitamin', '/ˈvaɪtəmɪn/', '维生素', 'Oranges are a good source of vitamin C.', '橙子是维生素C的良好来源。'],
        ['fat-soluble', '/ˈfæt ˌsɑːljəbəl/', '脂溶性的', 'Vitamins A, D, E and K are fat-soluble.', '维生素A、D、E、K是脂溶性的。'],
        ['provitamin', '/proʊˈvaɪtəmɪn/', '维生素原', 'Beta-carotene is a provitamin that the body converts to vitamin A.', 'β-胡萝卜素是一种维生素原，身体会把它转化为维生素A。'],
        ['retinol', '/ˈretɪnɔːl/', '视黄醇（维生素A）', 'Retinol is important for good vision.', '视黄醇对良好的视力很重要。'],
        ['beta-carotene', '/ˌbeɪtə ˈkærətiːn/', 'β-胡萝卜素', 'Carrots are rich in beta-carotene.', '胡萝卜富含β-胡萝卜素。'],
        ['vitamin D', '/ˈvaɪtəmɪn diː/', '维生素D', 'Your skin makes vitamin D when exposed to sunlight.', '皮肤在阳光照射下会合成维生素D。'],
        ['cholecalciferol', '/ˌkoʊləkælˈsɪfərɔːl/', '胆钙化醇（维生素D3）', 'Cholecalciferol is the form of vitamin D made in the skin.', '胆钙化醇是皮肤合成的维生素D形式。'],
        ['calcitriol', '/ˌkælsɪˈtraɪɔːl/', '骨化三醇（活性维生素D）', 'The kidneys convert vitamin D into calcitriol.', '肾脏把维生素D转化为骨化三醇。'],
        ['tocopherol', '/toʊˈkɑːfərɔːl/', '生育酚（维生素E）', 'Tocopherol acts as an antioxidant in cell membranes.', '生育酚在细胞膜中起抗氧化作用。'],
        ['vitamin K', '/ˈvaɪtəmɪn keɪ/', '维生素K', 'Vitamin K is necessary for blood clotting.', '维生素K是血液凝固所必需的。'],
        ['phylloquinone', '/ˌfɪloʊˈkwɪnoʊn/', '叶绿醌（维生素K1）', 'Green leafy vegetables are rich in phylloquinone.', '绿叶蔬菜富含叶绿醌。'],
      ],
    },
    {
      name: '水溶性维生素（B 族与 C）',
      tip: '按编号记：B1 thiamine、B2 riboflavin、B3 niacin、B5 pantothenic acid、B6 pyridoxine、B7 biotin、B9 folate、B12 cobalamin，C 是 ascorbic acid。',
      words: [
        ['water-soluble', '/ˈwɔːtər ˌsɑːljəbəl/', '水溶性的', 'B vitamins and vitamin C are water-soluble.', 'B族维生素和维生素C是水溶性的。'],
        ['thiamine', '/ˈθaɪəmɪn/', '硫胺素（维生素B1）', 'Thiamine helps the body turn carbohydrates into energy.', '硫胺素帮助身体把碳水化合物转化为能量。'],
        ['riboflavin', '/ˌraɪboʊˈfleɪvɪn/', '核黄素（维生素B2）', 'Milk is a good source of riboflavin.', '牛奶是核黄素的良好来源。'],
        ['niacin', '/ˈnaɪəsɪn/', '烟酸（维生素B3）', 'A lack of niacin causes a disease called pellagra.', '缺乏烟酸会导致一种叫糙皮病的疾病。'],
        ['pantothenic acid', '/ˌpæntəˈθenɪk ˈæsɪd/', '泛酸（维生素B5）', 'Pantothenic acid is part of coenzyme A.', '泛酸是辅酶A的组成部分。'],
        ['pyridoxine', '/ˌpɪrɪˈdɑːksiːn/', '吡哆醇（维生素B6）', 'Pyridoxine is needed for protein metabolism.', '蛋白质代谢需要吡哆醇。'],
        ['biotin', '/ˈbaɪətɪn/', '生物素（维生素B7）', 'Biotin helps the body use fats and carbohydrates.', '生物素帮助身体利用脂肪和碳水化合物。'],
        ['folate', '/ˈfoʊleɪt/', '叶酸（维生素B9，天然形式）', 'Pregnant women need extra folate.', '孕妇需要额外补充叶酸。'],
        ['folic acid', '/ˈfoʊlɪk ˈæsɪd/', '叶酸（合成形式）', 'Folic acid is added to enriched bread and cereal.', '强化面包和麦片中添加了合成叶酸。'],
        ['cobalamin', '/koʊˈbæləmɪn/', '钴胺素（维生素B12）', 'Vegans may need to take cobalamin supplements.', '纯素食者可能需要补充钴胺素。'],
        ['intrinsic factor', '/ɪnˈtrɪnzɪk ˈfæktər/', '内因子', 'Vitamin B12 needs intrinsic factor to be absorbed.', '维生素B12需要内因子才能被吸收。'],
        ['ascorbic acid', '/əˈskɔːrbɪk ˈæsɪd/', '抗坏血酸（维生素C）', 'Ascorbic acid improves the absorption of iron.', '抗坏血酸能促进铁的吸收。'],
        ['choline', '/ˈkoʊliːn/', '胆碱', 'Eggs are one of the best sources of choline.', '鸡蛋是胆碱的最佳来源之一。'],
      ],
    },
    {
      name: '维生素缺乏与过量疾病',
      tip: '把“营养素 → 缺乏病”配对记：C→scurvy，D→rickets / osteomalacia，B1→beriberi，B3→pellagra，A→night blindness，B12/叶酸→megaloblastic anemia。',
      words: [
        ['scurvy', '/ˈskɜːrvi/', '坏血病（缺维生素C）', 'Sailors used to get scurvy because they ate no fresh fruit.', '过去水手因吃不到新鲜水果而患坏血病。'],
        ['rickets', '/ˈrɪkɪts/', '佝偻病（儿童缺维生素D）', 'Rickets is caused by a lack of vitamin D in children.', '佝偻病是儿童缺乏维生素D引起的。'],
        ['osteomalacia', '/ˌɑːstioʊməˈleɪʃiə/', '骨软化症（成人缺维生素D）', 'Osteomalacia is the adult form of rickets.', '骨软化症是成人型的佝偻病。'],
        ['beriberi', '/ˌberiˈberi/', '脚气病（缺维生素B1）', 'Beriberi is caused by thiamine deficiency.', '脚气病由硫胺素缺乏引起。'],
        ['pellagra', '/pəˈlæɡrə/', '糙皮病（缺烟酸）', 'Pellagra causes dermatitis, diarrhea and dementia.', '糙皮病会引起皮炎、腹泻和痴呆。'],
        ['night blindness', '/naɪt ˈblaɪndnəs/', '夜盲症（缺维生素A）', 'Night blindness is an early sign of vitamin A deficiency.', '夜盲症是维生素A缺乏的早期征兆。'],
        ['xerophthalmia', '/ˌzɪrɑːfˈθælmiə/', '干眼症', 'Severe vitamin A deficiency can lead to xerophthalmia.', '严重的维生素A缺乏会导致干眼症。'],
        ['megaloblastic anemia', '/ˌmeɡəloʊˈblæstɪk əˈniːmiə/', '巨幼细胞性贫血', 'Folate deficiency causes megaloblastic anemia.', '叶酸缺乏会引起巨幼细胞性贫血。'],
        ['pernicious anemia', '/pərˈnɪʃəs əˈniːmiə/', '恶性贫血（缺内因子致B12吸收障碍）', 'Pernicious anemia is treated with vitamin B12 injections.', '恶性贫血通过注射维生素B12治疗。'],
        ['neural tube defect', '/ˈnʊrəl tuːb ˈdiːfekt/', '神经管缺陷', 'Folic acid before pregnancy lowers the risk of a neural tube defect.', '孕前补充叶酸能降低神经管缺陷风险。'],
        ['Wernicke-Korsakoff syndrome', '/ˈvɛrnɪkə ˈkɔːrsəkɔːf ˈsɪndroʊm/', '韦尼克-科尔萨科夫综合征（酗酒致B1缺乏）', 'Wernicke-Korsakoff syndrome is common in people with alcoholism.', '韦尼克-科尔萨科夫综合征常见于酗酒者。'],
        ['hypervitaminosis', '/ˌhaɪpərˌvaɪtəmɪˈnoʊsɪs/', '维生素过多症', 'Hypervitaminosis A can occur from taking too many supplements.', '服用过多补充剂可能导致维生素A过多症。'],
      ],
    },
    {
      name: '常量矿物质',
      tip: '每天需要量 > 100 毫克的矿物质：钙 Ca、磷 P、镁 Mg、钠 Na、钾 K、氯 Cl、硫 S。',
      words: [
        ['mineral', '/ˈmɪnərəl/', '矿物质', 'Calcium is the most abundant mineral in the body.', '钙是人体中含量最多的矿物质。'],
        ['major mineral', '/ˈmeɪdʒər ˈmɪnərəl/', '常量矿物质', 'Calcium and potassium are major minerals.', '钙和钾都是常量矿物质。'],
        ['calcium', '/ˈkælsiəm/', '钙', 'Dairy products are high in calcium.', '乳制品含钙量高。'],
        ['phosphorus', '/ˈfɑːsfərəs/', '磷', 'Phosphorus works with calcium to build strong bones.', '磷与钙一起构建强壮的骨骼。'],
        ['magnesium', '/mæɡˈniːziəm/', '镁', 'Leafy greens and nuts are good sources of magnesium.', '绿叶菜和坚果是镁的良好来源。'],
        ['sodium', '/ˈsoʊdiəm/', '钠', 'Processed foods are often high in sodium.', '加工食品通常含钠量高。'],
        ['potassium', '/pəˈtæsiəm/', '钾', 'Bananas are famous for their potassium.', '香蕉以富含钾而闻名。'],
        ['chloride', '/ˈklɔːraɪd/', '氯化物；氯离子', 'Table salt is made of sodium and chloride.', '食盐由钠和氯离子组成。'],
        ['sulfur', '/ˈsʌlfər/', '硫', 'Sulfur is found in some amino acids.', '某些氨基酸中含有硫。'],
        ['electrolyte', '/ɪˈlektrəlaɪt/', '电解质', 'Sodium and potassium are important electrolytes.', '钠和钾是重要的电解质。'],
      ],
    },
    {
      name: '微量矿物质（trace）',
      tip: '铁家族一起记：iron、heme / nonheme iron、ferritin 铁蛋白（储存）、transferrin 转铁蛋白（运输）；缺碘→goiter，铁过载→hemochromatosis。',
      words: [
        ['trace element', '/treɪs ˈelɪmənt/', '微量元素', 'Zinc is a trace element needed in very small amounts.', '锌是一种只需极少量的微量元素。'],
        ['iron', '/ˈaɪərn/', '铁', 'Red meat is a rich source of iron.', '红肉是铁的丰富来源。'],
        ['heme iron', '/hiːm ˈaɪərn/', '血红素铁', 'Heme iron from meat is absorbed more easily than plant iron.', '肉类中的血红素铁比植物中的铁更容易吸收。'],
        ['nonheme iron', '/ˌnɑːnˈhiːm ˈaɪərn/', '非血红素铁', 'Vitamin C increases the absorption of nonheme iron.', '维生素C能增加非血红素铁的吸收。'],
        ['ferritin', '/ˈferɪtɪn/', '铁蛋白（储存铁）', 'Low serum ferritin shows that iron stores are low.', '血清铁蛋白低说明铁储备不足。'],
        ['transferrin', '/trænsˈferɪn/', '转铁蛋白', 'Transferrin carries iron in the blood.', '转铁蛋白在血液中运输铁。'],
        ['zinc', '/zɪŋk/', '锌', 'Zinc supports the immune system and wound healing.', '锌能支持免疫系统和伤口愈合。'],
        ['iodine', '/ˈaɪədaɪn/', '碘', 'Iodine is added to salt to prevent thyroid problems.', '盐中加碘以预防甲状腺问题。'],
        ['selenium', '/səˈliːniəm/', '硒', 'Brazil nuts are very high in selenium.', '巴西坚果的硒含量非常高。'],
        ['copper', '/ˈkɑːpər/', '铜', 'Copper helps the body use iron.', '铜帮助身体利用铁。'],
        ['fluoride', '/ˈflɔːraɪd/', '氟化物', 'Fluoride helps prevent tooth decay.', '氟化物有助于预防蛀牙。'],
        ['manganese', '/ˈmæŋɡəniːz/', '锰', 'Whole grains and nuts provide manganese.', '全谷物和坚果提供锰。'],
        ['chromium', '/ˈkroʊmiəm/', '铬', 'Chromium may help insulin work better.', '铬可能有助于胰岛素更好地发挥作用。'],
        ['molybdenum', '/məˈlɪbdənəm/', '钼', 'Molybdenum is needed by several enzymes.', '有几种酶需要钼。'],
        ['goiter', '/ˈɡɔɪtər/', '甲状腺肿（缺碘）', 'Iodine deficiency can cause goiter.', '缺碘会引起甲状腺肿。'],
        ['hemochromatosis', '/ˌhiːməˌkroʊməˈtoʊsɪs/', '血色病（铁过载）', 'People with hemochromatosis absorb too much iron.', '血色病患者会吸收过多的铁。'],
        ['Keshan disease', '/ˈkeʃɑːn dɪˈziːz/', '克山病（缺硒）', 'Keshan disease is a heart disease linked to selenium deficiency.', '克山病是一种与缺硒有关的心脏病。'],
      ],
    },
    {
      name: '消化酶（-ase 结尾）',
      tip: '-ase 结尾 = “酶”，前面是它分解的对象：amyl-ase 分解淀粉、lip-ase 分解脂肪、prote-ase 分解蛋白质、lact-ase 分解乳糖。-ogen 结尾是“酶原”（未激活）。',
      words: [
        ['amylase', '/ˈæmɪleɪs/', '淀粉酶', 'Amylase breaks starch into smaller sugars.', '淀粉酶把淀粉分解成更小的糖。'],
        ['salivary amylase', '/ˈsæləveri ˈæmɪleɪs/', '唾液淀粉酶', 'Salivary amylase breaks down starch in the mouth.', '唾液淀粉酶在口腔中分解淀粉。'],
        ['lipase', '/ˈlaɪpeɪs/', '脂肪酶', 'Pancreatic lipase digests most dietary fat.', '胰脂肪酶消化大部分膳食脂肪。'],
        ['protease', '/ˈproʊtieɪs/', '蛋白酶', 'A protease breaks proteins into peptides.', '蛋白酶把蛋白质分解成肽。'],
        ['lactase', '/ˈlækteɪs/', '乳糖酶', 'People who lack lactase cannot digest milk sugar well.', '缺乏乳糖酶的人不能很好地消化乳糖。'],
        ['sucrase', '/ˈsuːkreɪs/', '蔗糖酶', 'Sucrase splits sucrose into glucose and fructose.', '蔗糖酶把蔗糖分解成葡萄糖和果糖。'],
        ['maltase', '/ˈmɔːlteɪs/', '麦芽糖酶', 'Maltase breaks maltose into two glucose molecules.', '麦芽糖酶把麦芽糖分解成两个葡萄糖分子。'],
        ['zymogen', '/ˈzaɪmədʒən/', '酶原', 'A zymogen is an inactive form of an enzyme.', '酶原是酶的无活性形式。'],
        ['pepsinogen', '/pepˈsɪnədʒən/', '胃蛋白酶原', 'Stomach acid converts pepsinogen into pepsin.', '胃酸把胃蛋白酶原转化为胃蛋白酶。'],
        ['pepsin', '/ˈpepsɪn/', '胃蛋白酶', 'Pepsin begins the digestion of protein.', '胃蛋白酶开始对蛋白质进行消化。'],
        ['trypsin', '/ˈtrɪpsɪn/', '胰蛋白酶', 'Trypsin digests protein in the small intestine.', '胰蛋白酶在小肠中消化蛋白质。'],
        ['chymotrypsin', '/ˌkaɪmoʊˈtrɪpsɪn/', '糜蛋白酶（胰凝乳蛋白酶）', 'Chymotrypsin works together with trypsin.', '糜蛋白酶和胰蛋白酶协同工作。'],
        ['carboxypeptidase', '/kɑːrˌbɑːksiˈpeptɪdeɪs/', '羧肽酶', 'Carboxypeptidase removes amino acids from the end of a peptide.', '羧肽酶从肽链末端切下氨基酸。'],
      ],
    },
    {
      name: '代谢途径（-lysis 分解 / -genesis 生成）',
      tip: '-lysis = 分解（glycolysis 糖酵解、lipolysis 脂肪分解），-genesis = 生成（gluconeogenesis 糖异生、lipogenesis 脂肪生成）。',
      words: [
        ['glycolysis', '/ɡlaɪˈkɑːləsɪs/', '糖酵解', 'Glycolysis breaks glucose into two smaller molecules.', '糖酵解把葡萄糖分解成两个更小的分子。'],
        ['glycogenolysis', '/ˌɡlaɪkədʒəˈnɑːləsɪs/', '糖原分解', 'Glucagon stimulates glycogenolysis in the liver.', '胰高血糖素刺激肝脏中的糖原分解。'],
        ['glycogenesis', '/ˌɡlaɪkoʊˈdʒenəsɪs/', '糖原合成', 'After a meal, insulin promotes glycogenesis.', '饭后胰岛素会促进糖原合成。'],
        ['gluconeogenesis', '/ˌɡluːkoʊˌniːoʊˈdʒenəsɪs/', '糖异生', 'During fasting, the liver makes new glucose through gluconeogenesis.', '禁食期间，肝脏通过糖异生合成新的葡萄糖。'],
        ['lipolysis', '/lɪˈpɑːləsɪs/', '脂肪分解', 'Exercise increases lipolysis in fat cells.', '运动会增加脂肪细胞中的脂肪分解。'],
        ['lipogenesis', '/ˌlɪpoʊˈdʒenəsɪs/', '脂肪生成', 'Eating too much sugar can increase lipogenesis in the liver.', '吃太多糖会增加肝脏的脂肪生成。'],
        ['ketogenesis', '/ˌkiːtoʊˈdʒenəsɪs/', '酮体生成', 'Ketogenesis increases during long periods of fasting.', '长时间禁食时酮体生成会增加。'],
        ['proteolysis', '/ˌproʊtiˈɑːləsɪs/', '蛋白质水解', 'Severe stress increases muscle proteolysis.', '严重应激会增加肌肉蛋白质分解。'],
        ['hydrolysis', '/haɪˈdrɑːləsɪs/', '水解', 'Digestive enzymes break down food by hydrolysis.', '消化酶通过水解分解食物。'],
        ['beta-oxidation', '/ˌbeɪtə ˌɑːksɪˈdeɪʃən/', 'β-氧化', 'Fatty acids are broken down by beta-oxidation.', '脂肪酸通过β-氧化被分解。'],
        ['pyruvate', '/paɪˈruːveɪt/', '丙酮酸（盐）', 'Glycolysis produces two molecules of pyruvate.', '糖酵解产生两分子丙酮酸。'],
        ['acetyl-CoA', '/əˌsiːtəl koʊˈeɪ/', '乙酰辅酶A', 'Acetyl-CoA enters the citric acid cycle.', '乙酰辅酶A进入柠檬酸循环。'],
        ['citric acid cycle', '/ˈsɪtrɪk ˈæsɪd ˈsaɪkəl/', '柠檬酸循环（三羧酸循环）', 'The citric acid cycle takes place in the mitochondria.', '柠檬酸循环在线粒体中进行。'],
        ['electron transport chain', '/ɪˈlektrɑːn ˈtrænspɔːrt tʃeɪn/', '电子传递链', 'The electron transport chain produces most of the ATP.', '电子传递链产生大部分ATP。'],
        ['oxidative phosphorylation', '/ˈɑːksɪdeɪtɪv ˌfɑːsfərɪˈleɪʃən/', '氧化磷酸化', 'Oxidative phosphorylation requires oxygen.', '氧化磷酸化需要氧气。'],
        ['adenosine triphosphate', '/əˈdenəsiːn traɪˈfɑːsfeɪt/', '三磷酸腺苷（ATP）', 'Adenosine triphosphate is the energy currency of the cell.', '三磷酸腺苷是细胞的能量货币。'],
        ['mitochondria', '/ˌmaɪtəˈkɑːndriə/', '线粒体', 'Mitochondria are called the powerhouses of the cell.', '线粒体被称为细胞的动力工厂。'],
        ['deamination', '/diːˌæmɪˈneɪʃən/', '脱氨基作用', 'Deamination removes the nitrogen group from an amino acid.', '脱氨基作用去除氨基酸上的氮基团。'],
        ['transamination', '/ˌtrænsæmɪˈneɪʃən/', '转氨基作用', 'The body makes nonessential amino acids by transamination.', '身体通过转氨基作用合成非必需氨基酸。'],
        ['urea cycle', '/juˈriːə ˈsaɪkəl/', '尿素循环', 'The urea cycle takes place in the liver.', '尿素循环在肝脏中进行。'],
        ['Cori cycle', '/ˈkɔːri ˈsaɪkəl/', '科里循环（乳酸循环）', 'In the Cori cycle, lactate from muscle becomes glucose in the liver.', '在科里循环中，肌肉产生的乳酸在肝脏中变回葡萄糖。'],
        ['coenzyme', '/koʊˈenzaɪm/', '辅酶', 'Many B vitamins act as coenzymes.', '许多B族维生素起辅酶的作用。'],
        ['cofactor', '/ˈkoʊˌfæktər/', '辅因子', 'Magnesium is a cofactor for hundreds of enzymes.', '镁是数百种酶的辅因子。'],
        ['ketosis', '/kiːˈtoʊsɪs/', '酮症', 'A very low-carb diet can put the body into ketosis.', '极低碳水饮食会使身体进入酮症状态。'],
      ],
    },
    {
      name: '常见酸类（-ic acid）',
      tip: '“-ic acid”= ……酸：citric 柠檬酸、lactic 乳酸、uric 尿酸、oxalic 草酸、phytic 植酸。与之对应的盐类常以 -ate 结尾（lactate、oxalate、phytate）。',
      words: [
        ['citric acid', '/ˈsɪtrɪk ˈæsɪd/', '柠檬酸', 'Lemons are rich in citric acid.', '柠檬富含柠檬酸。'],
        ['lactic acid', '/ˈlæktɪk ˈæsɪd/', '乳酸', 'Bacteria produce lactic acid when they ferment milk.', '细菌发酵牛奶时会产生乳酸。'],
        ['uric acid', '/ˈjʊrɪk ˈæsɪd/', '尿酸', 'High uric acid levels can cause gout.', '尿酸水平高会引起痛风。'],
        ['oxalic acid', '/ɑːkˈsælɪk ˈæsɪd/', '草酸', 'Spinach contains oxalic acid, which binds calcium.', '菠菜含有会结合钙的草酸。'],
        ['phytic acid', '/ˈfaɪtɪk ˈæsɪd/', '植酸', 'Soaking beans reduces their phytic acid.', '浸泡豆子能减少其中的植酸。'],
        ['acetic acid', '/əˈsiːtɪk ˈæsɪd/', '醋酸（乙酸）', 'Vinegar contains acetic acid.', '醋含有醋酸。'],
        ['nucleic acid', '/nuːˈkleɪɪk ˈæsɪd/', '核酸', 'DNA is a nucleic acid.', 'DNA是一种核酸。'],
        ['bile acid', '/baɪl ˈæsɪd/', '胆汁酸', 'The liver makes bile acids from cholesterol.', '肝脏用胆固醇合成胆汁酸。'],
        ['hydrochloric acid', '/ˌhaɪdrəˈklɔːrɪk ˈæsɪd/', '盐酸（胃酸）', 'Hydrochloric acid in the stomach kills many bacteria.', '胃里的盐酸能杀死许多细菌。'],
      ],
    },
    {
      name: '抗氧化与炎症',
      tip: 'anti- 对抗：antioxidant 抗氧化剂；oxid- 与氧化有关；-kine / -oid / -glandin 是炎症相关信号分子。',
      words: [
        ['oxidation', '/ˌɑːksɪˈdeɪʃən/', '氧化', 'The oxidation of nutrients releases energy.', '营养素的氧化会释放能量。'],
        ['antioxidant', '/ˌæntiˈɑːksɪdənt/', '抗氧化剂', 'Berries are full of antioxidants.', '浆果富含抗氧化剂。'],
        ['free radical', '/friː ˈrædɪkəl/', '自由基', 'A free radical can damage cells.', '自由基会损伤细胞。'],
        ['reactive oxygen species', '/riˈæktɪv ˈɑːksɪdʒən ˈspiːʃiːz/', '活性氧（ROS）', 'Intense exercise produces reactive oxygen species.', '高强度运动会产生活性氧。'],
        ['oxidative stress', '/ˈɑːksɪdeɪtɪv stres/', '氧化应激', 'Smoking increases oxidative stress in the body.', '吸烟会增加体内的氧化应激。'],
        ['glutathione', '/ˌɡluːtəˈθaɪoʊn/', '谷胱甘肽', 'Glutathione is the body\'s main internal antioxidant.', '谷胱甘肽是人体内主要的抗氧化物。'],
        ['inflammation', '/ˌɪnfləˈmeɪʃən/', '炎症', 'A poor diet may increase inflammation.', '不良饮食可能加重炎症。'],
        ['cytokine', '/ˈsaɪtəkaɪn/', '细胞因子', 'A cytokine is a signaling protein released during inflammation.', '细胞因子是炎症时释放的信号蛋白。'],
        ['eicosanoid', '/aɪˈkoʊsənɔɪd/', '类二十烷酸', 'Omega-3 fats produce less inflammatory eicosanoids.', 'ω-3脂肪产生的类二十烷酸致炎性较弱。'],
        ['prostaglandin', '/ˌprɑːstəˈɡlændɪn/', '前列腺素', 'Aspirin blocks the production of prostaglandins.', '阿司匹林阻断前列腺素的生成。'],
      ],
    },
    {
      name: '水、电解质与酸碱平衡',
      tip: 'intra- 内、extra- 外：intracellular / extracellular fluid；-osis 表示“状态”：acidosis 酸中毒、alkalosis 碱中毒、osmosis 渗透。',
      words: [
        ['fluid balance', '/ˈfluːɪd ˈbæləns/', '体液平衡', 'The kidneys control fluid balance.', '肾脏控制体液平衡。'],
        ['intracellular fluid', '/ˌɪntrəˈseljələr ˈfluːɪd/', '细胞内液', 'Potassium is the main ion in intracellular fluid.', '钾是细胞内液中的主要离子。'],
        ['extracellular fluid', '/ˌekstrəˈseljələr ˈfluːɪd/', '细胞外液', 'Sodium is the main ion in extracellular fluid.', '钠是细胞外液中的主要离子。'],
        ['osmosis', '/ɑːzˈmoʊsɪs/', '渗透（作用）', 'Water moves across cell membranes by osmosis.', '水通过渗透作用穿过细胞膜。'],
        ['osmolality', '/ˌɑːzmoʊˈlæləti/', '渗透压摩尔浓度', 'A formula with high osmolality may cause diarrhea.', '高渗透压的配方可能引起腹泻。'],
        ['pH', '/ˌpiː ˈeɪtʃ/', '酸碱度（pH值）', 'Normal blood pH is about 7.4.', '正常血液的pH值约为7.4。'],
        ['acid-base balance', '/ˈæsɪd beɪs ˈbæləns/', '酸碱平衡', 'The lungs and kidneys maintain acid-base balance.', '肺和肾维持酸碱平衡。'],
        ['acidosis', '/ˌæsɪˈdoʊsɪs/', '酸中毒', 'Uncontrolled diabetes can cause acidosis.', '未控制的糖尿病可引起酸中毒。'],
        ['alkalosis', '/ˌælkəˈloʊsɪs/', '碱中毒', 'Severe vomiting can lead to alkalosis.', '严重呕吐可导致碱中毒。'],
        ['buffer', '/ˈbʌfər/', '缓冲剂（缓冲系统）', 'Bicarbonate acts as a buffer in the blood.', '碳酸氢盐在血液中起缓冲作用。'],
        ['bicarbonate', '/baɪˈkɑːrbəneɪt/', '碳酸氢盐', 'The pancreas releases bicarbonate to neutralize stomach acid.', '胰腺释放碳酸氢盐来中和胃酸。'],
        ['antidiuretic hormone', '/ˌæntiˌdaɪjəˈretɪk ˈhɔːrmoʊn/', '抗利尿激素（ADH）', 'Antidiuretic hormone tells the kidneys to save water.', '抗利尿激素让肾脏保留水分。'],
      ],
    },
  ],
});
