VOCAB.push({
  id: 'anatomy',
  name: '解剖与生理学',
  icon: '🫀',
  desc: '人体结构、消化吸收、器官系统与激素',
  groups: [
    {
      name: '细胞与组织',
      tip: 'cyto- / -cyte 表示“细胞”；-some 表示“小体”；epi- 在…上面（epithelium 上皮）。',
      words: [
        ['anatomy', '/əˈnætəmi/', '解剖学', 'Anatomy is the study of the structure of the body.', '解剖学是研究身体结构的学科。'],
        ['physiology', '/ˌfɪziˈɑːlədʒi/', '生理学', 'Physiology explains how the body works.', '生理学解释身体是如何运作的。'],
        ['cell', '/sel/', '细胞', 'The cell is the basic unit of life.', '细胞是生命的基本单位。'],
        ['cell membrane', '/sel ˈmembreɪn/', '细胞膜', 'The cell membrane controls what enters the cell.', '细胞膜控制物质进入细胞。'],
        ['nucleus', '/ˈnuːkliəs/', '细胞核', 'The nucleus contains the cell\'s DNA.', '细胞核含有细胞的DNA。'],
        ['cytoplasm', '/ˈsaɪtəplæzəm/', '细胞质', 'Glycolysis takes place in the cytoplasm.', '糖酵解在细胞质中进行。'],
        ['ribosome', '/ˈraɪbəsoʊm/', '核糖体', 'Proteins are made on the ribosome.', '蛋白质在核糖体上合成。'],
        ['gene', '/dʒiːn/', '基因', 'A gene carries the code for making a protein.', '基因携带合成蛋白质的密码。'],
        ['receptor', '/rɪˈseptər/', '受体', 'Insulin binds to a receptor on the cell surface.', '胰岛素与细胞表面的受体结合。'],
        ['tissue', '/ˈtɪʃuː/', '组织', 'Muscle tissue can contract.', '肌肉组织能够收缩。'],
        ['epithelium', '/ˌepɪˈθiːliəm/', '上皮（组织）', 'The intestinal epithelium absorbs nutrients.', '肠上皮负责吸收营养素。'],
        ['connective tissue', '/kəˈnektɪv ˈtɪʃuː/', '结缔组织', 'Bone and blood are types of connective tissue.', '骨骼和血液都属于结缔组织。'],
        ['organ', '/ˈɔːrɡən/', '器官', 'The skin is the largest organ of the body.', '皮肤是人体最大的器官。'],
        ['organ system', '/ˈɔːrɡən ˈsɪstəm/', '器官系统', 'Each organ system has a special job.', '每个器官系统都有特定的功能。'],
      ],
    },
    {
      name: '上消化道（口腔→胃）',
      tip: '按食物经过的顺序记：oral cavity 口腔 → pharynx 咽 → esophagus 食道 → stomach 胃 → pyloric sphincter 幽门。gastr- 表示“胃”。',
      words: [
        ['digestive system', '/daɪˈdʒestɪv ˈsɪstəm/', '消化系统', 'The digestive system breaks food into nutrients.', '消化系统把食物分解成营养素。'],
        ['gastrointestinal tract', '/ˌɡæstroʊɪnˈtestɪnəl trækt/', '胃肠道（GI道）', 'The gastrointestinal tract runs from the mouth to the anus.', '胃肠道从口腔一直延伸到肛门。'],
        ['oral cavity', '/ˈɔːrəl ˈkævəti/', '口腔', 'Digestion starts in the oral cavity.', '消化从口腔开始。'],
        ['saliva', '/səˈlaɪvə/', '唾液', 'Saliva moistens food and starts the digestion of starch.', '唾液湿润食物并开始消化淀粉。'],
        ['bolus', '/ˈboʊləs/', '食团', 'Chewed food forms a soft bolus before swallowing.', '咀嚼后的食物在吞咽前形成柔软的食团。'],
        ['pharynx', '/ˈfærɪŋks/', '咽', 'Food passes through the pharynx when you swallow.', '吞咽时食物经过咽部。'],
        ['epiglottis', '/ˌepɪˈɡlɑːtɪs/', '会厌', 'The epiglottis stops food from entering the airway.', '会厌阻止食物进入气道。'],
        ['esophagus', '/ɪˈsɑːfəɡəs/', '食道', 'The esophagus carries food from the mouth to the stomach.', '食道把食物从口腔送到胃。'],
        ['sphincter', '/ˈsfɪŋktər/', '括约肌', 'A sphincter is a ring of muscle that opens and closes.', '括约肌是一圈能开合的肌肉。'],
        ['lower esophageal sphincter', '/ˈloʊər ɪˌsɑːfəˈdʒiːəl ˈsfɪŋktər/', '食管下括约肌', 'A weak lower esophageal sphincter can cause reflux.', '食管下括约肌松弛会引起反流。'],
        ['stomach', '/ˈstʌmək/', '胃', 'The stomach mixes food with acid.', '胃把食物与胃酸混合。'],
        ['gastric juice', '/ˈɡæstrɪk dʒuːs/', '胃液', 'Gastric juice contains acid and enzymes.', '胃液含有酸和酶。'],
        ['parietal cell', '/pəˈraɪətəl sel/', '壁细胞', 'The parietal cell secretes acid and intrinsic factor.', '壁细胞分泌胃酸和内因子。'],
        ['chief cell', '/tʃiːf sel/', '主细胞', 'The chief cell releases pepsinogen.', '主细胞释放胃蛋白酶原。'],
        ['mucus', '/ˈmjuːkəs/', '黏液', 'Mucus protects the stomach lining from acid.', '黏液保护胃黏膜免受胃酸侵蚀。'],
        ['chyme', '/kaɪm/', '食糜', 'The stomach turns food into a thick liquid called chyme.', '胃把食物变成一种叫食糜的浓稠液体。'],
        ['pyloric sphincter', '/paɪˈlɔːrɪk ˈsfɪŋktər/', '幽门括约肌', 'The pyloric sphincter controls how fast chyme leaves the stomach.', '幽门括约肌控制食糜离开胃的速度。'],
        ['gastric emptying', '/ˈɡæstrɪk ˈemptiɪŋ/', '胃排空', 'Fat slows gastric emptying.', '脂肪会减慢胃排空。'],
      ],
    },
    {
      name: '小肠与大肠（-um 结尾的肠段）',
      tip: '小肠三段都以 -um 结尾：duodenum → jejunum → ileum；大肠：cecum → colon → rectum。entero- 表示“肠”。',
      words: [
        ['small intestine', '/smɔːl ɪnˈtestɪn/', '小肠', 'The small intestine is about six meters long.', '小肠大约有六米长。'],
        ['duodenum', '/ˌduːəˈdiːnəm/', '十二指肠', 'Iron and calcium are mainly absorbed in the duodenum.', '铁和钙主要在十二指肠吸收。'],
        ['jejunum', '/dʒɪˈdʒuːnəm/', '空肠', 'Most nutrients are absorbed in the jejunum.', '大多数营养素在空肠被吸收。'],
        ['ileum', '/ˈɪliəm/', '回肠', 'Vitamin B12 and bile salts are absorbed in the ileum.', '维生素B12和胆盐在回肠被吸收。'],
        ['ileocecal valve', '/ˌɪlioʊˈsiːkəl vælv/', '回盲瓣', 'The ileocecal valve separates the small and large intestine.', '回盲瓣把小肠和大肠隔开。'],
        ['villi', '/ˈvɪlaɪ/', '绒毛（复数）', 'Villi increase the surface area of the small intestine.', '绒毛增加了小肠的表面积。'],
        ['microvilli', '/ˌmaɪkroʊˈvɪlaɪ/', '微绒毛', 'Microvilli cover the surface of intestinal cells.', '微绒毛覆盖在肠细胞表面。'],
        ['brush border', '/brʌʃ ˈbɔːrdər/', '刷状缘', 'Lactase is found on the brush border.', '乳糖酶位于刷状缘上。'],
        ['enterocyte', '/ˈentəroʊsaɪt/', '肠上皮细胞', 'Each enterocyte absorbs nutrients from the gut.', '每个肠上皮细胞都从肠道吸收营养素。'],
        ['lacteal', '/ˈlæktiəl/', '乳糜管', 'Absorbed fat enters a lacteal in each villus.', '被吸收的脂肪进入每个绒毛中的乳糜管。'],
        ['large intestine', '/lɑːrdʒ ɪnˈtestɪn/', '大肠', 'The large intestine absorbs water and electrolytes.', '大肠吸收水和电解质。'],
        ['cecum', '/ˈsiːkəm/', '盲肠', 'The cecum is the first part of the large intestine.', '盲肠是大肠的第一部分。'],
        ['colon', '/ˈkoʊlən/', '结肠', 'Fiber feeds the bacteria in the colon.', '纤维为结肠中的细菌提供养分。'],
        ['rectum', '/ˈrektəm/', '直肠', 'The rectum stores waste before it leaves the body.', '直肠在废物排出体外前将其储存。'],
        ['feces', '/ˈfiːsiːz/', '粪便', 'Fiber increases the bulk of feces.', '纤维会增加粪便的体积。'],
        ['peristalsis', '/ˌperɪˈstɔːlsɪs/', '（肠胃）蠕动', 'Peristalsis moves food through the digestive tract.', '蠕动推动食物在消化道中前进。'],
        ['segmentation', '/ˌseɡmenˈteɪʃən/', '分节运动', 'Segmentation mixes chyme with digestive juices.', '分节运动把食糜和消化液混合。'],
        ['gut microbiota', '/ɡʌt ˌmaɪkroʊbaɪˈoʊtə/', '肠道菌群', 'A high-fiber diet supports a healthy gut microbiota.', '高纤维饮食有助于维持健康的肠道菌群。'],
      ],
    },
    {
      name: '肝胆胰（消化附属器官）',
      tip: 'hepat- 表示“肝”（hepatocyte 肝细胞）；chole- 表示“胆”；exo- 向外分泌（exocrine），endo- 向内分泌（endocrine）。',
      words: [
        ['liver', '/ˈlɪvər/', '肝脏', 'The liver processes nutrients after absorption.', '肝脏在营养素被吸收后对其进行加工。'],
        ['hepatocyte', '/ˈhepətoʊsaɪt/', '肝细胞', 'Each hepatocyte can store glycogen.', '每个肝细胞都能储存糖原。'],
        ['portal vein', '/ˈpɔːrtəl veɪn/', '门静脉', 'The portal vein carries nutrients from the intestine to the liver.', '门静脉把营养素从肠道输送到肝脏。'],
        ['gallbladder', '/ˈɡɔːlˌblædər/', '胆囊', 'The gallbladder stores bile.', '胆囊储存胆汁。'],
        ['bile', '/baɪl/', '胆汁', 'Bile helps digest fat.', '胆汁帮助消化脂肪。'],
        ['enterohepatic circulation', '/ˌentəroʊhɪˈpætɪk ˌsɜːrkjəˈleɪʃən/', '肠肝循环', 'Bile salts are recycled through enterohepatic circulation.', '胆盐通过肠肝循环被回收利用。'],
        ['pancreas', '/ˈpæŋkriəs/', '胰腺', 'The pancreas makes digestive enzymes and insulin.', '胰腺分泌消化酶和胰岛素。'],
        ['pancreatic juice', '/ˌpæŋkriˈætɪk dʒuːs/', '胰液', 'Pancreatic juice contains bicarbonate and enzymes.', '胰液含有碳酸氢盐和消化酶。'],
        ['exocrine', '/ˈeksəkrɪn/', '外分泌的', 'The exocrine pancreas releases enzymes into the intestine.', '胰腺的外分泌部把酶释放到肠道。'],
      ],
    },
    {
      name: '消化道与食欲激素',
      tip: '消化激素多以 -in 结尾：gastrin 胃泌素、secretin 促胰液素、ghrelin 饥饿素、leptin 瘦素。ghrelin 让你饿（“grr”肚子叫），leptin 让你饱。',
      words: [
        ['hormone', '/ˈhɔːrmoʊn/', '激素', 'Insulin is a hormone made by the pancreas.', '胰岛素是胰腺分泌的一种激素。'],
        ['gastrin', '/ˈɡæstrɪn/', '胃泌素', 'Gastrin stimulates the stomach to release acid.', '胃泌素刺激胃分泌胃酸。'],
        ['secretin', '/sɪˈkriːtɪn/', '促胰液素', 'Secretin tells the pancreas to release bicarbonate.', '促胰液素让胰腺释放碳酸氢盐。'],
        ['cholecystokinin', '/ˌkoʊləˌsɪstoʊˈkaɪnɪn/', '缩胆囊素（CCK）', 'Cholecystokinin makes the gallbladder contract.', '缩胆囊素使胆囊收缩。'],
        ['ghrelin', '/ˈɡrelɪn/', '饥饿素（胃饥饿素）', 'Ghrelin makes you feel hungry.', '饥饿素会让你感到饥饿。'],
        ['leptin', '/ˈleptɪn/', '瘦素', 'Leptin tells the brain that you have enough stored fat.', '瘦素告诉大脑体内储存的脂肪已经足够。'],
        ['glucagon-like peptide-1', '/ˈɡluːkəɡɑːn laɪk ˈpeptaɪd wʌn/', '胰高血糖素样肽-1（GLP-1）', 'Glucagon-like peptide-1 slows stomach emptying and reduces appetite.', '胰高血糖素样肽-1能减慢胃排空、降低食欲。'],
      ],
    },
    {
      name: '血液与循环系统',
      tip: 'hem- / hemat- 表示“血”（hemoglobin、hematocrit）；cardi- 表示“心”；systolic 收缩压（高值），diastolic 舒张压（低值）。',
      words: [
        ['circulatory system', '/ˈsɜːrkjələtɔːri ˈsɪstəm/', '循环系统', 'The circulatory system delivers nutrients to every cell.', '循环系统把营养素输送到每个细胞。'],
        ['heart', '/hɑːrt/', '心脏', 'The heart pumps blood around the body.', '心脏把血液泵送到全身。'],
        ['artery', '/ˈɑːrtəri/', '动脉', 'An artery carries blood away from the heart.', '动脉把血液从心脏运出。'],
        ['vein', '/veɪn/', '静脉', 'A vein carries blood back to the heart.', '静脉把血液运回心脏。'],
        ['capillary', '/ˈkæpəleri/', '毛细血管', 'Nutrients pass from capillaries into the tissues.', '营养素从毛细血管进入组织。'],
        ['plasma', '/ˈplæzmə/', '血浆', 'Plasma is the liquid part of blood.', '血浆是血液的液体部分。'],
        ['serum', '/ˈsɪrəm/', '血清', 'Serum is plasma without clotting factors.', '血清是去除了凝血因子的血浆。'],
        ['red blood cell', '/red blʌd sel/', '红细胞', 'Each red blood cell carries oxygen.', '每个红细胞都携带氧气。'],
        ['white blood cell', '/waɪt blʌd sel/', '白细胞', 'A white blood cell fights infection.', '白细胞抵抗感染。'],
        ['platelet', '/ˈpleɪtlət/', '血小板', 'Platelets help blood to clot.', '血小板帮助血液凝固。'],
        ['hemoglobin', '/ˈhiːməɡloʊbɪn/', '血红蛋白', 'Iron is needed to make hemoglobin.', '合成血红蛋白需要铁。'],
        ['hematocrit', '/hɪˈmætəkrɪt/', '红细胞压积（血细胞比容）', 'A low hematocrit may indicate anemia.', '红细胞压积低可能提示贫血。'],
        ['blood pressure', '/blʌd ˈpreʃər/', '血压', 'Too much salt can raise blood pressure.', '盐摄入过多会升高血压。'],
        ['systolic', '/sɪˈstɑːlɪk/', '收缩期的（收缩压）', 'Her systolic pressure was 140.', '她的收缩压是140。'],
        ['diastolic', '/ˌdaɪəˈstɑːlɪk/', '舒张期的（舒张压）', 'A normal diastolic pressure is below 80.', '正常舒张压低于80。'],
        ['lymphatic system', '/lɪmˈfætɪk ˈsɪstəm/', '淋巴系统', 'Absorbed fats enter the lymphatic system first.', '被吸收的脂肪首先进入淋巴系统。'],
      ],
    },
    {
      name: '呼吸系统',
      tip: 'respir- 呼吸；pulmo- 肺；alveoli 是 alveolus（肺泡）的复数。',
      words: [
        ['respiratory system', '/ˈrespərətɔːri ˈsɪstəm/', '呼吸系统', 'The respiratory system brings oxygen into the body.', '呼吸系统把氧气带入体内。'],
        ['lung', '/lʌŋ/', '肺', 'Oxygen enters the blood in the lungs.', '氧气在肺部进入血液。'],
        ['alveoli', '/ælˈviːəlaɪ/', '肺泡（复数）', 'Gas exchange takes place in the alveoli.', '气体交换在肺泡中进行。'],
        ['oxygen', '/ˈɑːksɪdʒən/', '氧气', 'Muscles need oxygen to burn fat.', '肌肉需要氧气来燃烧脂肪。'],
        ['carbon dioxide', '/ˈkɑːrbən daɪˈɑːksaɪd/', '二氧化碳', 'We breathe out carbon dioxide.', '我们呼出二氧化碳。'],
        ['respiratory quotient', '/ˈrespərətɔːri ˈkwoʊʃənt/', '呼吸商（RQ）', 'The respiratory quotient for pure carbohydrate is 1.0.', '纯碳水化合物的呼吸商是1.0。'],
      ],
    },
    {
      name: '内分泌系统（-crine / gland 腺）',
      tip: 'endo- 内 + -crine 分泌 = 内分泌；adrenal = ad（靠近）+ renal（肾）= 肾上腺；thyro- 甲状腺；-one 结尾多为类固醇激素。',
      words: [
        ['endocrine system', '/ˈendəkrɪn ˈsɪstəm/', '内分泌系统', 'The endocrine system uses hormones to send messages.', '内分泌系统利用激素传递信息。'],
        ['gland', '/ɡlænd/', '腺体', 'A gland makes and releases substances such as hormones.', '腺体分泌和释放激素等物质。'],
        ['hypothalamus', '/ˌhaɪpoʊˈθæləməs/', '下丘脑', 'The hypothalamus helps control hunger and thirst.', '下丘脑帮助控制饥饿和口渴。'],
        ['pituitary gland', '/pɪˈtuːɪteri ɡlænd/', '垂体', 'The pituitary gland is often called the master gland.', '垂体常被称为“主腺体”。'],
        ['thyroid', '/ˈθaɪrɔɪd/', '甲状腺', 'The thyroid controls your metabolic rate.', '甲状腺控制着你的代谢速率。'],
        ['thyroid hormone', '/ˈθaɪrɔɪd ˈhɔːrmoʊn/', '甲状腺激素', 'Iodine is needed to make thyroid hormone.', '合成甲状腺激素需要碘。'],
        ['parathyroid hormone', '/ˌpærəˈθaɪrɔɪd ˈhɔːrmoʊn/', '甲状旁腺激素（PTH）', 'Parathyroid hormone raises blood calcium.', '甲状旁腺激素使血钙升高。'],
        ['adrenal gland', '/əˈdriːnəl ɡlænd/', '肾上腺', 'The adrenal gland releases adrenaline during stress.', '肾上腺在压力下释放肾上腺素。'],
        ['cortisol', '/ˈkɔːrtɪsɔːl/', '皮质醇', 'Cortisol levels rise when you are stressed.', '压力大时皮质醇水平会升高。'],
        ['aldosterone', '/ælˈdɑːstəroʊn/', '醛固酮', 'Aldosterone makes the kidneys keep sodium.', '醛固酮使肾脏保留钠。'],
        ['growth hormone', '/ɡroʊθ ˈhɔːrmoʊn/', '生长激素', 'Growth hormone is released mostly during sleep.', '生长激素主要在睡眠中分泌。'],
        ['estrogen', '/ˈestrədʒən/', '雌激素', 'Estrogen helps protect bone density in women.', '雌激素有助于保护女性的骨密度。'],
        ['testosterone', '/tesˈtɑːstəroʊn/', '睾酮', 'Testosterone supports muscle growth.', '睾酮有助于肌肉生长。'],
        ['islets of Langerhans', '/ˈaɪləts əv ˈlɑːŋərhɑːnz/', '胰岛', 'Insulin is made in the islets of Langerhans.', '胰岛素由胰岛分泌。'],
        ['beta cell', '/ˈbeɪtə sel/', 'β细胞（胰岛素分泌细胞）', 'In type 1 diabetes the immune system destroys each beta cell.', '在1型糖尿病中，免疫系统会破坏β细胞。'],
      ],
    },
    {
      name: '泌尿系统（renal / nephr- 肾）',
      tip: 'renal（拉丁）和 nephr-（希腊）都表示“肾”：renal failure 肾衰竭、nephron 肾单位、nephropathy 肾病。',
      words: [
        ['urinary system', '/ˈjʊrəneri ˈsɪstəm/', '泌尿系统', 'The urinary system removes waste from the blood.', '泌尿系统清除血液中的废物。'],
        ['kidney', '/ˈkɪdni/', '肾脏', 'The kidney filters about 180 liters of blood plasma a day.', '肾脏每天过滤大约180升血浆。'],
        ['renal', '/ˈriːnəl/', '肾的；肾脏的', 'A renal dietitian works with dialysis patients.', '肾脏营养师为透析患者服务。'],
        ['nephron', '/ˈnefrɑːn/', '肾单位', 'Each kidney contains about one million nephrons.', '每个肾脏含有约一百万个肾单位。'],
        ['glomerulus', '/ɡloʊˈmerjələs/', '肾小球', 'The glomerulus filters blood.', '肾小球过滤血液。'],
        ['renin', '/ˈriːnɪn/', '肾素', 'The kidney releases renin when blood pressure falls.', '血压下降时肾脏会释放肾素。'],
        ['erythropoietin', '/ɪˌrɪθroʊˈpɔɪətɪn/', '促红细胞生成素（EPO）', 'Damaged kidneys make less erythropoietin, which causes anemia.', '受损的肾脏分泌的促红细胞生成素减少，导致贫血。'],
        ['urine', '/ˈjʊrɪn/', '尿液', 'Pale yellow urine is a sign of good hydration.', '淡黄色的尿液是水分充足的标志。'],
        ['bladder', '/ˈblædər/', '膀胱', 'The bladder stores urine.', '膀胱储存尿液。'],
      ],
    },
    {
      name: '骨骼与肌肉',
      tip: 'osteo- 表示“骨”：osteoblast 成骨细胞（blast 建造）、osteoclast 破骨细胞（clast 打碎）；三种肌肉：skeletal、smooth、cardiac。',
      words: [
        ['skeletal system', '/ˈskelətəl ˈsɪstəm/', '骨骼系统', 'The skeletal system supports and protects the body.', '骨骼系统支撑和保护身体。'],
        ['bone', '/boʊn/', '骨', 'Calcium and vitamin D keep bone strong.', '钙和维生素D使骨骼强壮。'],
        ['bone mineral density', '/boʊn ˈmɪnərəl ˈdensəti/', '骨密度', 'Weight-bearing exercise improves bone mineral density.', '负重运动能提高骨密度。'],
        ['osteoblast', '/ˈɑːstioʊblæst/', '成骨细胞', 'An osteoblast builds new bone.', '成骨细胞构建新骨。'],
        ['osteoclast', '/ˈɑːstioʊklæst/', '破骨细胞', 'An osteoclast breaks down old bone.', '破骨细胞分解旧骨。'],
        ['cartilage', '/ˈkɑːrtəlɪdʒ/', '软骨', 'Cartilage protects the ends of bones in a joint.', '软骨保护关节中骨的末端。'],
        ['joint', '/dʒɔɪnt/', '关节', 'The knee is the largest joint in the body.', '膝盖是人体最大的关节。'],
        ['skeletal muscle', '/ˈskelətəl ˈmʌsəl/', '骨骼肌', 'Skeletal muscle stores a lot of glycogen.', '骨骼肌储存大量糖原。'],
        ['smooth muscle', '/smuːð ˈmʌsəl/', '平滑肌', 'Smooth muscle in the gut wall controls peristalsis.', '肠壁的平滑肌控制蠕动。'],
        ['cardiac muscle', '/ˈkɑːrdiæk ˈmʌsəl/', '心肌', 'Cardiac muscle never gets tired.', '心肌从不疲劳。'],
        ['muscle fiber', '/ˈmʌsəl ˈfaɪbər/', '肌纤维', 'Each muscle fiber is a long, thin cell.', '每条肌纤维都是一个细长的细胞。'],
        ['tendon', '/ˈtendən/', '肌腱', 'A tendon connects muscle to bone.', '肌腱把肌肉连接到骨骼上。'],
        ['ligament', '/ˈlɪɡəmənt/', '韧带', 'A ligament connects bone to bone.', '韧带把骨与骨连接起来。'],
        ['adipose tissue', '/ˈædɪpoʊs ˈtɪʃuː/', '脂肪组织', 'Adipose tissue stores energy as fat.', '脂肪组织以脂肪的形式储存能量。'],
        ['brown adipose tissue', '/braʊn ˈædɪpoʊs ˈtɪʃuː/', '棕色脂肪组织', 'Brown adipose tissue burns energy to make heat.', '棕色脂肪组织燃烧能量产生热量。'],
      ],
    },
    {
      name: '神经与免疫系统',
      tip: 'neuro- 表示“神经”；-cyte 细胞（lymphocyte 淋巴细胞）；transmitter 传递者。',
      words: [
        ['nervous system', '/ˈnɜːrvəs ˈsɪstəm/', '神经系统', 'The nervous system controls muscle movement.', '神经系统控制肌肉运动。'],
        ['brain', '/breɪn/', '大脑', 'The brain uses about 20 percent of the body\'s energy.', '大脑消耗身体约20%的能量。'],
        ['spinal cord', '/ˈspaɪnəl kɔːrd/', '脊髓', 'The spinal cord connects the brain to the rest of the body.', '脊髓把大脑与身体其他部位连接起来。'],
        ['neuron', '/ˈnʊrɑːn/', '神经元', 'A neuron sends electrical signals.', '神经元传递电信号。'],
        ['neurotransmitter', '/ˌnʊroʊˈtrænzmɪtər/', '神经递质', 'Serotonin is a neurotransmitter made from tryptophan.', '血清素是一种由色氨酸合成的神经递质。'],
        ['serotonin', '/ˌserəˈtoʊnɪn/', '血清素（5-羟色胺）', 'Serotonin affects mood and appetite.', '血清素影响情绪和食欲。'],
        ['vagus nerve', '/ˈveɪɡəs nɜːrv/', '迷走神经', 'The vagus nerve connects the gut and the brain.', '迷走神经连接肠道和大脑。'],
        ['immune system', '/ɪˈmjuːn ˈsɪstəm/', '免疫系统', 'Good nutrition supports a strong immune system.', '良好的营养支持强大的免疫系统。'],
        ['lymphocyte', '/ˈlɪmfəsaɪt/', '淋巴细胞', 'A low lymphocyte count may reflect malnutrition.', '淋巴细胞计数低可能反映营养不良。'],
      ],
    },
  ],
});
