VOCAB.push({
  id: 'food',
  name: '食物营养与食品科学',
  icon: '🥦',
  desc: '食物分类、植物化学物、食品科学、标签与膳食参考、食品安全',
  groups: [
    {
      name: '谷物（grain）',
      tip: '一粒全谷物 = bran 麸皮 + germ 胚芽 + endosperm 胚乳；refined 精制谷物只剩胚乳。',
      words: [
        ['whole grain', '/hoʊl ɡreɪn/', '全谷物', 'Brown rice is a whole grain.', '糙米是一种全谷物。'],
        ['refined grain', '/rɪˈfaɪnd ɡreɪn/', '精制谷物', 'White flour is a refined grain with the bran removed.', '白面粉是去除了麸皮的精制谷物。'],
        ['bran', '/bræn/', '麸皮', 'Bran is the outer layer of the grain and is rich in fiber.', '麸皮是谷粒的外层，富含纤维。'],
        ['germ', '/dʒɜːrm/', '胚芽', 'The germ is the part of the grain that can grow into a new plant.', '胚芽是谷粒中能长成新植株的部分。'],
        ['endosperm', '/ˈendoʊspɜːrm/', '胚乳', 'White flour is made mostly from the endosperm.', '白面粉主要由胚乳制成。'],
        ['milling', '/ˈmɪlɪŋ/', '碾磨（加工）', 'Milling removes much of the fiber from wheat.', '碾磨会去除小麦中的大部分纤维。'],
        ['cereal', '/ˈsɪriəl/', '谷物；麦片', 'Wheat, rice and corn are cereal crops.', '小麦、水稻和玉米都是谷类作物。'],
        ['gluten', '/ˈɡluːtən/', '麸质；面筋', 'People with celiac disease must avoid gluten.', '乳糜泻患者必须避免麸质。'],
        ['oat', '/oʊt/', '燕麦', 'Oat bran can help lower cholesterol.', '燕麦麸有助于降低胆固醇。'],
        ['barley', '/ˈbɑːrli/', '大麦', 'Barley contains gluten.', '大麦含有麸质。'],
        ['buckwheat', '/ˈbʌkwiːt/', '荞麦', 'Despite its name, buckwheat is gluten-free.', '虽然名字里有“麦”，荞麦其实不含麸质。'],
        ['quinoa', '/ˈkiːnwɑː/', '藜麦', 'Quinoa is a complete plant protein.', '藜麦是一种完全植物蛋白。'],
        ['brown rice', '/braʊn raɪs/', '糙米', 'Brown rice has more fiber than white rice.', '糙米的纤维比白米多。'],
      ],
    },
    {
      name: '蔬果、豆类与坚果',
      tip: 'legume 豆类（lentil 小扁豆、chickpea 鹰嘴豆、soybean 大豆）；cruciferous 十字花科（西兰花、卷心菜）；starchy vegetable 淀粉类蔬菜按主食计。',
      words: [
        ['vegetable', '/ˈvedʒtəbəl/', '蔬菜', 'Try to fill half your plate with vegetables.', '尽量让蔬菜占满盘子的一半。'],
        ['leafy green', '/ˈliːfi ɡriːn/', '绿叶蔬菜', 'Spinach is a leafy green rich in folate.', '菠菜是一种富含叶酸的绿叶蔬菜。'],
        ['cruciferous vegetable', '/kruːˈsɪfərəs ˈvedʒtəbəl/', '十字花科蔬菜', 'Broccoli is a cruciferous vegetable.', '西兰花是一种十字花科蔬菜。'],
        ['starchy vegetable', '/ˈstɑːrtʃi ˈvedʒtəbəl/', '淀粉类蔬菜', 'Corn and peas are starchy vegetables.', '玉米和豌豆是淀粉类蔬菜。'],
        ['tuber', '/ˈtuːbər/', '块茎类（食物）', 'The potato is a tuber that grows underground.', '土豆是一种生长在地下的块茎。'],
        ['fruit', '/fruːt/', '水果', 'Whole fruit is better than fruit juice.', '完整的水果比果汁更好。'],
        ['berry', '/ˈberi/', '浆果', 'A blueberry is a small berry full of antioxidants.', '蓝莓是一种富含抗氧化剂的小浆果。'],
        ['citrus', '/ˈsɪtrəs/', '柑橘类（水果）', 'Citrus fruits are high in vitamin C.', '柑橘类水果富含维生素C。'],
        ['legume', '/ˈleɡjuːm/', '豆类', 'Lentils and chickpeas are legumes.', '小扁豆和鹰嘴豆都是豆类。'],
        ['lentil', '/ˈlentəl/', '小扁豆', 'Lentils cook quickly and are high in protein.', '小扁豆煮得快，而且蛋白质含量高。'],
        ['chickpea', '/ˈtʃɪkpiː/', '鹰嘴豆', 'Hummus is made from chickpeas.', '鹰嘴豆泥是用鹰嘴豆做的。'],
        ['soybean', '/ˈsɔɪbiːn/', '大豆', 'Tofu is made from soybeans.', '豆腐是用大豆做的。'],
        ['tofu', '/ˈtoʊfuː/', '豆腐', 'Tofu is a good plant protein.', '豆腐是一种优质植物蛋白。'],
        ['nut', '/nʌt/', '坚果', 'A handful of nuts makes a healthy snack.', '一小把坚果是健康的零食。'],
        ['seed', '/siːd/', '种子', 'Chia seeds are high in fiber.', '奇亚籽富含纤维。'],
      ],
    },
    {
      name: '动物性食物与乳制品',
      tip: 'dairy 乳制品；poultry 禽肉；lean 瘦的；organ meat 内脏（肝、肾等）营养密度很高。',
      words: [
        ['dairy', '/ˈderi/', '乳制品', 'Milk, cheese and yogurt are dairy foods.', '牛奶、奶酪和酸奶都是乳制品。'],
        ['yogurt', '/ˈjoʊɡərt/', '酸奶', 'Yogurt is often easier to digest than milk.', '酸奶通常比牛奶更容易消化。'],
        ['poultry', '/ˈpoʊltri/', '禽肉；家禽', 'Chicken and turkey are types of poultry.', '鸡肉和火鸡肉都属于禽肉。'],
        ['seafood', '/ˈsiːfuːd/', '海鲜', 'Seafood is a good source of iodine.', '海鲜是碘的良好来源。'],
        ['fatty fish', '/ˈfæti fɪʃ/', '多脂鱼', 'Eat fatty fish such as salmon twice a week.', '每周吃两次三文鱼等多脂鱼。'],
        ['lean meat', '/liːn miːt/', '瘦肉', 'Lean meat has less fat.', '瘦肉的脂肪较少。'],
        ['red meat', '/red miːt/', '红肉', 'Beef and pork are red meat.', '牛肉和猪肉都是红肉。'],
        ['processed meat', '/ˈprɑːsest miːt/', '加工肉制品', 'Bacon and sausage are processed meat.', '培根和香肠都是加工肉制品。'],
        ['organ meat', '/ˈɔːrɡən miːt/', '动物内脏', 'Liver is an organ meat rich in vitamin A.', '肝脏是一种富含维生素A的动物内脏。'],
        ['egg yolk', '/eɡ joʊk/', '蛋黄', 'The egg yolk contains most of the egg\'s vitamins.', '蛋黄含有鸡蛋中的大部分维生素。'],
      ],
    },
    {
      name: '食物类型与膳食模式',
      tip: '-arian / -an 表示“…的人”：vegetarian 素食者、vegan 纯素者；lacto 奶、ovo 蛋。',
      words: [
        ['whole food', '/hoʊl fuːd/', '天然完整食物（未加工食物）', 'An apple is a whole food.', '苹果是一种未经加工的天然完整食物。'],
        ['fermented food', '/fərˈmentɪd fuːd/', '发酵食品', 'Kimchi is a fermented food.', '泡菜是一种发酵食品。'],
        ['ultra-processed food', '/ˌʌltrə ˈprɑːsest fuːd/', '超加工食品', 'Chips and candy are ultra-processed foods.', '薯片和糖果都是超加工食品。'],
        ['functional food', '/ˈfʌŋkʃənəl fuːd/', '功能性食品', 'Yogurt with probiotics is a functional food.', '含益生菌的酸奶是一种功能性食品。'],
        ['nutraceutical', '/ˌnuːtrəˈsuːtɪkəl/', '营养保健品', 'Fish oil capsules are a popular nutraceutical.', '鱼油胶囊是一种很受欢迎的营养保健品。'],
        ['plant-based diet', '/ˈplænt beɪst ˈdaɪət/', '植物性饮食', 'A plant-based diet focuses on vegetables, grains and legumes.', '植物性饮食以蔬菜、谷物和豆类为主。'],
        ['vegetarian', '/ˌvedʒəˈteriən/', '素食者；素食的', 'A vegetarian does not eat meat.', '素食者不吃肉。'],
        ['lacto-ovo vegetarian', '/ˌlæktoʊ ˌoʊvoʊ ˌvedʒəˈteriən/', '蛋奶素食者', 'A lacto-ovo vegetarian eats eggs and dairy but no meat.', '蛋奶素食者吃蛋和奶，但不吃肉。'],
        ['vegan', '/ˈviːɡən/', '纯素食者；纯素的', 'A vegan avoids all animal products.', '纯素食者不吃任何动物性产品。'],
        ['Mediterranean diet', '/ˌmedɪtəˈreɪniən ˈdaɪət/', '地中海饮食', 'The Mediterranean diet is rich in olive oil, fish and vegetables.', '地中海饮食富含橄榄油、鱼和蔬菜。'],
      ],
    },
    {
      name: '植物化学物（-oid / -in / -ol）',
      tip: 'phyto- 表示“植物”：phytochemical 植物化学物、phytoestrogen 植物雌激素；按颜色记：红 lycopene、橙 carotenoid、紫 anthocyanin、黄绿 lutein。',
      words: [
        ['phytochemical', '/ˌfaɪtoʊˈkemɪkəl/', '植物化学物', 'Colorful vegetables contain many phytochemicals.', '色彩丰富的蔬菜含有许多植物化学物。'],
        ['polyphenol', '/ˌpɑːliˈfiːnɔːl/', '多酚', 'Green tea is rich in polyphenols.', '绿茶富含多酚。'],
        ['flavonoid', '/ˈfleɪvənɔɪd/', '类黄酮', 'Dark chocolate contains a flavonoid that may benefit the heart.', '黑巧克力含有一种可能对心脏有益的类黄酮。'],
        ['isoflavone', '/ˌaɪsoʊˈfleɪvoʊn/', '异黄酮', 'Soy foods are rich in isoflavones.', '大豆食品富含异黄酮。'],
        ['phytoestrogen', '/ˌfaɪtoʊˈestrədʒən/', '植物雌激素', 'Isoflavones are a type of phytoestrogen.', '异黄酮是一类植物雌激素。'],
        ['catechin', '/ˈkætəkɪn/', '儿茶素', 'Green tea contains a catechin called EGCG.', '绿茶含有一种叫EGCG的儿茶素。'],
        ['carotenoid', '/kəˈrɑːtənɔɪd/', '类胡萝卜素', 'Carotenoids give carrots their orange color.', '类胡萝卜素使胡萝卜呈现橙色。'],
        ['lycopene', '/ˈlaɪkəpiːn/', '番茄红素', 'Tomatoes are rich in lycopene.', '番茄富含番茄红素。'],
        ['lutein', '/ˈluːtiːn/', '叶黄素', 'Lutein protects the eyes from damage.', '叶黄素保护眼睛免受损伤。'],
        ['zeaxanthin', '/ˌziːəˈzænθɪn/', '玉米黄质', 'Zeaxanthin is found in corn and egg yolks.', '玉米黄质存在于玉米和蛋黄中。'],
        ['anthocyanin', '/ˌænθəˈsaɪənɪn/', '花青素', 'Anthocyanin gives blueberries their blue color.', '花青素使蓝莓呈现蓝色。'],
        ['resveratrol', '/rɪzˈverətrɔːl/', '白藜芦醇', 'Red grapes contain resveratrol.', '红葡萄含有白藜芦醇。'],
        ['glucosinolate', '/ˌɡluːkoʊˈsɪnəleɪt/', '硫代葡萄糖苷', 'Broccoli contains glucosinolates.', '西兰花含有硫代葡萄糖苷。'],
        ['curcumin', '/ˈkɜːrkjʊmɪn/', '姜黄素', 'Curcumin is the yellow compound in turmeric.', '姜黄素是姜黄中的黄色化合物。'],
      ],
    },
    {
      name: '益生菌、益生元与抗营养因子',
      tip: 'pro- 支持 + bio 生命 = probiotic 益生菌；pre- 在前 = prebiotic 益生元（菌的食物）；syn- 一起 = synbiotic 合生元。抗营养因子多以 -ate 结尾。',
      words: [
        ['probiotic', '/ˌproʊbaɪˈɑːtɪk/', '益生菌', 'Yogurt contains probiotic bacteria.', '酸奶含有益生菌。'],
        ['prebiotic', '/ˌpriːbaɪˈɑːtɪk/', '益生元', 'Onions and garlic contain prebiotic fiber.', '洋葱和大蒜含有益生元纤维。'],
        ['synbiotic', '/ˌsɪnbaɪˈɑːtɪk/', '合生元', 'A synbiotic combines a probiotic and a prebiotic.', '合生元把益生菌和益生元结合在一起。'],
        ['antinutrient', '/ˌæntiˈnuːtriənt/', '抗营养因子', 'An antinutrient can reduce the absorption of minerals.', '抗营养因子会降低矿物质的吸收。'],
        ['phytate', '/ˈfaɪteɪt/', '植酸盐', 'Phytate in whole grains can reduce zinc absorption.', '全谷物中的植酸盐会降低锌的吸收。'],
        ['oxalate', '/ˈɑːksəleɪt/', '草酸盐', 'Spinach is high in oxalate.', '菠菜的草酸盐含量高。'],
        ['tannin', '/ˈtænɪn/', '单宁（鞣酸）', 'Tannins in tea can block iron absorption.', '茶中的单宁会阻碍铁的吸收。'],
        ['goitrogen', '/ˈɡɔɪtrədʒən/', '致甲状腺肿物质', 'Raw cabbage contains a goitrogen.', '生卷心菜含有致甲状腺肿物质。'],
      ],
    },
    {
      name: '食品添加剂与甜味剂',
      tip: '-er / -ive 表示“…剂”：sweetener 甜味剂、thickener 增稠剂、stabilizer 稳定剂、preservative 防腐剂、additive 添加剂。',
      words: [
        ['food additive', '/fuːd ˈædətɪv/', '食品添加剂', 'A food additive is used to improve taste, color or shelf life.', '食品添加剂用于改善味道、颜色或延长保质期。'],
        ['preservative', '/prɪˈzɜːrvətɪv/', '防腐剂', 'Salt has been used as a preservative for centuries.', '盐作为防腐剂已被使用了几个世纪。'],
        ['emulsifier', '/ɪˈmʌlsɪfaɪər/', '乳化剂', 'Egg yolk acts as an emulsifier in mayonnaise.', '蛋黄在蛋黄酱中充当乳化剂。'],
        ['stabilizer', '/ˈsteɪbəlaɪzər/', '稳定剂', 'Ice cream contains a stabilizer to keep it smooth.', '冰淇淋含有稳定剂以保持顺滑。'],
        ['thickener', '/ˈθɪkənər/', '增稠剂', 'A thickener is added to liquids for patients with dysphagia.', '为吞咽困难患者在液体中添加增稠剂。'],
        ['monosodium glutamate', '/ˌmɑːnoʊˈsoʊdiəm ˈɡluːtəmeɪt/', '味精（谷氨酸钠，MSG）', 'Monosodium glutamate adds a savory taste.', '味精能增加鲜味。'],
        ['nitrite', '/ˈnaɪtraɪt/', '亚硝酸盐', 'Nitrite is used to cure ham and bacon.', '亚硝酸盐被用来腌制火腿和培根。'],
        ['generally recognized as safe', '/ˈdʒenərəli ˈrekəɡnaɪzd æz seɪf/', '一般认为安全（GRAS）', 'Salt and sugar are generally recognized as safe.', '盐和糖被列为“一般认为安全”的物质。'],
        ['sweetener', '/ˈswiːtnər/', '甜味剂', 'Honey is a natural sweetener.', '蜂蜜是一种天然甜味剂。'],
        ['added sugar', '/ˈædɪd ˈʃʊɡər/', '添加糖', 'Limit added sugar to less than 10 percent of daily calories.', '把添加糖限制在每日热量的10%以下。'],
        ['nonnutritive sweetener', '/ˌnɑːnˈnuːtrətɪv ˈswiːtnər/', '无营养甜味剂（零热量甜味剂）', 'A nonnutritive sweetener provides almost no calories.', '无营养甜味剂几乎不提供热量。'],
        ['artificial sweetener', '/ˌɑːrtɪˈfɪʃəl ˈswiːtnər/', '人工甜味剂', 'Many diet drinks use an artificial sweetener.', '许多无糖饮料使用人工甜味剂。'],
        ['aspartame', '/ˈæspərteɪm/', '阿斯巴甜', 'People with PKU must avoid aspartame.', '苯丙酮尿症患者必须避免阿斯巴甜。'],
        ['sucralose', '/ˈsuːkrəloʊs/', '三氯蔗糖', 'Sucralose is about 600 times sweeter than sugar.', '三氯蔗糖的甜度约为蔗糖的600倍。'],
        ['stevia', '/ˈstiːviə/', '甜菊糖', 'Stevia comes from the leaves of a plant.', '甜菊糖来自一种植物的叶子。'],
      ],
    },
    {
      name: '食品科学与烹调化学（-ation 过程）',
      tip: '-ation / -ization 表示“过程”：gelatinization 糊化、caramelization 焦糖化、coagulation 凝固、homogenization 均质化。',
      words: [
        ['food science', '/fuːd ˈsaɪəns/', '食品科学', 'Food science studies how food changes during processing.', '食品科学研究食物在加工中如何变化。'],
        ['Maillard reaction', '/maɪˈjɑːr riˈækʃən/', '美拉德反应', 'The Maillard reaction makes toast brown.', '美拉德反应使吐司变成褐色。'],
        ['caramelization', '/ˌkærəməlaɪˈzeɪʃən/', '焦糖化', 'Caramelization happens when sugar is heated.', '糖被加热时会发生焦糖化。'],
        ['enzymatic browning', '/ˌenzaɪˈmætɪk ˈbraʊnɪŋ/', '酶促褐变', 'Lemon juice prevents enzymatic browning of cut apples.', '柠檬汁能防止切开的苹果发生酶促褐变。'],
        ['gelatinization', '/dʒəˌlætɪnaɪˈzeɪʃən/', '（淀粉）糊化', 'Starch gelatinization thickens sauces.', '淀粉糊化使酱汁变稠。'],
        ['retrogradation', '/ˌretroʊɡreɪˈdeɪʃən/', '（淀粉）回生；老化', 'Retrogradation makes bread go stale.', '淀粉回生使面包变硬变陈。'],
        ['coagulation', '/koʊˌæɡjəˈleɪʃən/', '凝固', 'Heat causes the coagulation of egg proteins.', '加热会使蛋白质凝固。'],
        ['emulsion', '/ɪˈmʌlʃən/', '乳状液（乳化体系）', 'Mayonnaise is an emulsion of oil and water.', '蛋黄酱是油和水的乳状液。'],
        ['homogenization', '/həˌmɑːdʒənaɪˈzeɪʃən/', '均质化', 'Homogenization stops cream from rising to the top of milk.', '均质化使奶油不会浮到牛奶表面。'],
        ['rancidity', '/rænˈsɪdəti/', '（油脂）酸败', 'Oxygen and light speed up the rancidity of oils.', '氧气和光照会加速油脂酸败。'],
        ['smoke point', '/smoʊk pɔɪnt/', '烟点', 'Avocado oil has a high smoke point.', '牛油果油的烟点很高。'],
        ['leavening agent', '/ˈlevənɪŋ ˈeɪdʒənt/', '膨松剂', 'Baking soda is a leavening agent.', '小苏打是一种膨松剂。'],
        ['water activity', '/ˈwɔːtər ækˈtɪvəti/', '水分活度', 'Foods with low water activity spoil more slowly.', '水分活度低的食物变质得更慢。'],
        ['viscosity', '/vɪˈskɑːsəti/', '黏度', 'Thickened liquids have a higher viscosity.', '增稠后的液体黏度更高。'],
      ],
    },
    {
      name: '膳食参考摄入量（DRIs 家族）',
      tip: 'DRIs 是“大家族”：EAR（平均需要量）→ RDA（推荐量，满足97–98%人群）→ AI（数据不足时的适宜量）→ UL（最高上限）；AMDR 是宏量营养素供能比范围。',
      words: [
        ['Dietary Reference Intakes', '/ˈdaɪəteri ˈrefərəns ˈɪnteɪks/', '膳食营养素参考摄入量（DRIs）', 'The Dietary Reference Intakes are used to plan healthy diets.', '膳食营养素参考摄入量用于规划健康饮食。'],
        ['Estimated Average Requirement', '/ˈestɪmeɪtɪd ˈævərɪdʒ rɪˈkwaɪərmənt/', '平均需要量（EAR）', 'The Estimated Average Requirement meets the needs of half the population.', '平均需要量能满足一半人群的需要。'],
        ['Recommended Dietary Allowance', '/ˌrekəˈmendɪd ˈdaɪəteri əˈlaʊəns/', '推荐膳食营养素供给量（RDA）', 'The Recommended Dietary Allowance for vitamin C is about 75 to 90 milligrams.', '维生素C的推荐膳食供给量约为75至90毫克。'],
        ['Adequate Intake', '/ˈædɪkwət ˈɪnteɪk/', '适宜摄入量（AI）', 'An Adequate Intake is set when there is not enough data for an RDA.', '当数据不足以制定RDA时，就设定适宜摄入量。'],
        ['Tolerable Upper Intake Level', '/ˈtɑːlərəbəl ˈʌpər ˈɪnteɪk ˈlevəl/', '可耐受最高摄入量（UL）', 'Do not exceed the Tolerable Upper Intake Level for vitamin A.', '不要超过维生素A的可耐受最高摄入量。'],
        ['Acceptable Macronutrient Distribution Range', '/əkˈseptəbəl ˌmækroʊˈnuːtriənt ˌdɪstrɪˈbjuːʃən reɪndʒ/', '宏量营养素可接受范围（AMDR）', 'The Acceptable Macronutrient Distribution Range for carbohydrate is 45 to 65 percent of calories.', '碳水化合物的宏量营养素可接受范围是总热量的45%到65%。'],
        ['Estimated Energy Requirement', '/ˈestɪmeɪtɪd ˈenərdʒi rɪˈkwaɪərmənt/', '估计能量需要量（EER）', 'The Estimated Energy Requirement depends on age, sex, weight and activity.', '估计能量需要量取决于年龄、性别、体重和活动水平。'],
        ['dietary guidelines', '/ˈdaɪəteri ˈɡaɪdlaɪnz/', '膳食指南', 'The dietary guidelines recommend eating more whole grains.', '膳食指南建议多吃全谷物。'],
        ['MyPlate', '/maɪ pleɪt/', '我的餐盘（美国膳食指导图）', 'MyPlate shows that half your plate should be fruits and vegetables.', '“我的餐盘”显示你的盘子一半应该是水果和蔬菜。'],
        ['balanced diet', '/ˈbælənst ˈdaɪət/', '均衡饮食', 'A balanced diet contains all the food groups.', '均衡饮食包含所有食物类别。'],
        ['portion', '/ˈpɔːrʃən/', '份量；一份', 'Restaurant portions are often too large.', '餐厅的份量往往太大。'],
        ['nutrient density', '/ˈnuːtriənt ˈdensəti/', '营养密度', 'Spinach has a high nutrient density.', '菠菜的营养密度很高。'],
        ['energy density', '/ˈenərdʒi ˈdensəti/', '能量密度', 'Fried foods have a high energy density.', '油炸食品的能量密度很高。'],
        ['empty calories', '/ˈempti ˈkæləriz/', '空热量（只有热量没有营养）', 'Soda provides empty calories.', '汽水只提供空热量。'],
        ['moderation', '/ˌmɑːdəˈreɪʃən/', '适量；适度', 'You can enjoy sweets in moderation.', '你可以适量享用甜食。'],
      ],
    },
    {
      name: '食品标签与声称',
      tip: 'fortified 强化（加入原本没有的营养素），enriched 营养恢复（补回加工损失的营养素）——RD 考试常考区别。claim 声称：health claim 与 nutrient content claim。',
      words: [
        ['food label', '/fuːd ˈleɪbəl/', '食品标签', 'Always read the food label before you buy.', '购买前一定要阅读食品标签。'],
        ['nutrition facts', '/nuˈtrɪʃən fækts/', '营养成分表', 'The nutrition facts panel shows calories and nutrients.', '营养成分表显示热量和营养素含量。'],
        ['serving size', '/ˈsɜːrvɪŋ saɪz/', '每份分量', 'The serving size on this package is one cup.', '这个包装上标注的每份分量是一杯。'],
        ['daily value', '/ˈdeɪli ˈvæljuː/', '每日营养素参考值（%DV）', 'This cereal provides 20 percent of the daily value for iron.', '这种麦片提供了铁每日参考值的20%。'],
        ['ingredient list', '/ɪnˈɡriːdiənt lɪst/', '配料表', 'The ingredient list is ordered by weight.', '配料表按重量从多到少排列。'],
        ['health claim', '/helθ kleɪm/', '健康声称', 'A health claim links a food to a lower risk of disease.', '健康声称把某种食物与降低疾病风险联系起来。'],
        ['nutrient content claim', '/ˈnuːtriənt ˈkɑːntent kleɪm/', '营养素含量声称', '"Low fat" is a nutrient content claim.', '“低脂”是一种营养素含量声称。'],
        ['fortified', '/ˈfɔːrtɪfaɪd/', '强化的（额外添加营养素）', 'This milk is fortified with vitamin D.', '这种牛奶强化添加了维生素D。'],
        ['enriched', '/ɪnˈrɪtʃt/', '营养恢复的（补回加工损失）', 'Enriched flour has some B vitamins added back.', '营养强化面粉补回了一些B族维生素。'],
        ['organic', '/ɔːrˈɡænɪk/', '有机的', 'Organic vegetables are grown without synthetic pesticides.', '有机蔬菜在种植时不使用合成农药。'],
      ],
    },
    {
      name: '食品安全与致病菌',
      tip: '记住四大常考菌：Salmonella 沙门氏菌（禽蛋）、E. coli 大肠杆菌（生牛肉）、Listeria 李斯特菌（孕妇、冷藏即食品）、Clostridium botulinum 肉毒梭菌（罐头）。',
      words: [
        ['food safety', '/fuːd ˈseɪfti/', '食品安全', 'Washing your hands is basic food safety.', '洗手是基本的食品安全措施。'],
        ['contamination', '/kənˌtæmɪˈneɪʃən/', '污染', 'Contamination can happen during food storage.', '食物在储存过程中可能受到污染。'],
        ['cross-contamination', '/ˌkrɔːs kənˌtæmɪˈneɪʃən/', '交叉污染', 'Use separate cutting boards to avoid cross-contamination.', '使用不同的砧板以避免交叉污染。'],
        ['pathogen', '/ˈpæθədʒən/', '病原体', 'Salmonella is a common foodborne pathogen.', '沙门氏菌是一种常见的食源性病原体。'],
        ['foodborne illness', '/ˈfuːdbɔːrn ˈɪlnəs/', '食源性疾病', 'Undercooked chicken can cause foodborne illness.', '未煮熟的鸡肉会引起食源性疾病。'],
        ['Salmonella', '/ˌsælməˈnelə/', '沙门氏菌', 'Raw eggs may contain Salmonella.', '生鸡蛋可能含有沙门氏菌。'],
        ['E. coli', '/ˌiː ˈkoʊlaɪ/', '大肠杆菌', 'Undercooked ground beef can carry E. coli.', '未煮熟的牛肉馅可能带有大肠杆菌。'],
        ['Listeria', '/lɪˈstɪriə/', '李斯特菌', 'Pregnant women should avoid foods that may carry Listeria.', '孕妇应避免可能带有李斯特菌的食物。'],
        ['Clostridium botulinum', '/klɑːˈstrɪdiəm ˌbɑːtʃəˈlaɪnəm/', '肉毒梭菌', 'Improperly canned food can contain Clostridium botulinum.', '罐装不当的食品可能含有肉毒梭菌。'],
        ['norovirus', '/ˈnɔːroʊˌvaɪrəs/', '诺如病毒', 'Norovirus spreads easily on cruise ships.', '诺如病毒在游轮上很容易传播。'],
        ['temperature danger zone', '/ˈtemprətʃər ˈdeɪndʒər zoʊn/', '温度危险区（5–57°C / 41–135°F）', 'Bacteria grow fastest in the temperature danger zone.', '细菌在温度危险区内生长最快。'],
        ['food allergy', '/fuːd ˈælərdʒi/', '食物过敏', 'A peanut food allergy can be life-threatening.', '花生过敏可能危及生命。'],
        ['allergen', '/ˈælərdʒən/', '过敏原', 'Milk is a common allergen.', '牛奶是一种常见的过敏原。'],
        ['lactose intolerance', '/ˈlæktoʊs ɪnˈtɑːlərəns/', '乳糖不耐受', 'Lactose intolerance is very common in East Asia.', '乳糖不耐受在东亚非常普遍。'],
      ],
    },
    {
      name: '食品加工与储存',
      tip: '保存方法一起记：pasteurization 巴氏杀菌、irradiation 辐照、refrigeration 冷藏、fermentation 发酵、blanching 焯水。',
      words: [
        ['pasteurization', '/ˌpæstʃərəˈzeɪʃən/', '巴氏杀菌', 'Pasteurization kills harmful bacteria in milk.', '巴氏杀菌能杀死牛奶中的有害细菌。'],
        ['irradiation', '/ɪˌreɪdiˈeɪʃən/', '辐照（杀菌）', 'Irradiation can kill bacteria on spices.', '辐照可以杀死香料上的细菌。'],
        ['fermentation', '/ˌfɜːrmenˈteɪʃən/', '发酵', 'Fermentation turns milk into yogurt.', '发酵把牛奶变成酸奶。'],
        ['refrigeration', '/rɪˌfrɪdʒəˈreɪʃən/', '冷藏', 'Refrigeration slows the growth of bacteria.', '冷藏能减缓细菌的生长。'],
        ['blanching', '/ˈblæntʃɪŋ/', '焯水；热烫', 'Blanching vegetables before freezing keeps their color.', '冷冻前焯水能保持蔬菜的颜色。'],
        ['shelf life', '/ʃelf laɪf/', '保质期', 'Canned food has a long shelf life.', '罐头食品的保质期很长。'],
        ['expiration date', '/ˌekspəˈreɪʃən deɪt/', '到期日；截止日期', 'Check the expiration date on the milk carton.', '检查一下牛奶盒上的到期日。'],
      ],
    },
  ],
});
