VOCAB.push({
  id: 'sports',
  name: '运动营养学',
  icon: '🏃',
  desc: '能量系统、训练与身体成分、补剂、补水与营养时机',
  groups: [
    {
      name: '能量系统（aerobic / anaerobic）',
      tip: 'a- / an- 表示“无”：aerobic 有氧、anaerobic 无氧。三大供能系统：phosphagen（磷酸原，几秒）→ glycolytic（糖酵解，几十秒到两分钟）→ oxidative（有氧，长时间）。',
      words: [
        ['aerobic', '/eˈroʊbɪk/', '有氧的', 'Jogging is an aerobic exercise.', '慢跑是一种有氧运动。'],
        ['anaerobic', '/ˌæneˈroʊbɪk/', '无氧的', 'Sprinting relies mainly on anaerobic energy.', '短跑主要依靠无氧供能。'],
        ['phosphagen system', '/ˈfɑːsfədʒən ˈsɪstəm/', '磷酸原系统（ATP-PC系统）', 'The phosphagen system powers a 100-meter sprint.', '磷酸原系统为100米冲刺供能。'],
        ['phosphocreatine', '/ˌfɑːsfoʊˈkriːətiːn/', '磷酸肌酸', 'Phosphocreatine supplies energy for the first few seconds of a sprint.', '磷酸肌酸为冲刺的最初几秒提供能量。'],
        ['lactate', '/ˈlækteɪt/', '乳酸（盐）', 'Lactate builds up during intense exercise.', '剧烈运动时乳酸会堆积。'],
        ['lactate threshold', '/ˈlækteɪt ˈθreʃhoʊld/', '乳酸阈', 'Training can raise your lactate threshold.', '训练可以提高你的乳酸阈。'],
        ['VO2 max', '/ˌviː oʊ ˈtuː mæks/', '最大摄氧量', 'Elite runners have a very high VO2 max.', '精英跑者的最大摄氧量非常高。'],
        ['fat oxidation', '/fæt ˌɑːksɪˈdeɪʃən/', '脂肪氧化', 'Fat oxidation is highest during moderate exercise.', '脂肪氧化在中等强度运动时最高。'],
        ['glycogen sparing', '/ˈɡlaɪkədʒən ˈsperɪŋ/', '糖原节省', 'Endurance training causes glycogen sparing by burning more fat.', '耐力训练通过燃烧更多脂肪实现糖原节省。'],
        ['endurance', '/ɪnˈdʊrəns/', '耐力', 'Marathon running requires great endurance.', '马拉松需要极好的耐力。'],
        ['fatigue', '/fəˈtiːɡ/', '疲劳', 'Low glycogen levels cause fatigue.', '糖原水平低会导致疲劳。'],
        ['heart rate', '/hɑːrt reɪt/', '心率', 'Your heart rate increases during exercise.', '运动时你的心率会加快。'],
        ['excess post-exercise oxygen consumption', '/ɪkˈses ˌpoʊst ˈeksərsaɪz ˈɑːksɪdʒən kənˈsʌmpʃən/', '运动后过量氧耗（EPOC）', 'Excess post-exercise oxygen consumption keeps metabolism high after a workout.', '运动后过量氧耗使训练后代谢保持较高水平。'],
      ],
    },
    {
      name: '能量消耗与能量平衡',
      tip: 'TDEE = BMR/RMR（基础/静息代谢）+ TEF（食物热效应）+ 活动消耗；deficit 缺口 → 减重，surplus 盈余 → 增重。',
      words: [
        ['basal metabolic rate', '/ˈbeɪsəl ˌmetəˈbɑːlɪk reɪt/', '基础代谢率（BMR）', 'Muscle mass raises your basal metabolic rate.', '肌肉量会提高你的基础代谢率。'],
        ['resting metabolic rate', '/ˈrestɪŋ ˌmetəˈbɑːlɪk reɪt/', '静息代谢率（RMR）', 'Resting metabolic rate is the energy you burn at rest.', '静息代谢率是你在休息时消耗的能量。'],
        ['thermic effect of food', '/ˈθɜːrmɪk ɪˈfekt əv fuːd/', '食物热效应（TEF）', 'Protein has the highest thermic effect of food.', '蛋白质的食物热效应最高。'],
        ['energy expenditure', '/ˈenərdʒi ɪkˈspendɪtʃər/', '能量消耗', 'Running increases energy expenditure.', '跑步会增加能量消耗。'],
        ['total daily energy expenditure', '/ˈtoʊtəl ˈdeɪli ˈenərdʒi ɪkˈspendɪtʃər/', '每日总能量消耗（TDEE）', 'Athletes have a high total daily energy expenditure.', '运动员的每日总能量消耗很高。'],
        ['metabolic equivalent', '/ˌmetəˈbɑːlɪk ɪˈkwɪvələnt/', '代谢当量（MET）', 'Brisk walking is about four metabolic equivalents.', '快走约为四个代谢当量。'],
        ['energy balance', '/ˈenərdʒi ˈbæləns/', '能量平衡', 'Weight stays stable when you are in energy balance.', '处于能量平衡时体重保持稳定。'],
        ['caloric deficit', '/kəˈlɔːrɪk ˈdefɪsɪt/', '热量缺口', 'You need a caloric deficit to lose fat.', '减脂需要制造热量缺口。'],
        ['caloric surplus', '/kəˈlɔːrɪk ˈsɜːrpləs/', '热量盈余', 'A small caloric surplus helps build muscle.', '少量的热量盈余有助于增肌。'],
        ['physical activity', '/ˈfɪzɪkəl ækˈtɪvəti/', '身体活动', 'Adults need 150 minutes of physical activity a week.', '成年人每周需要150分钟的身体活动。'],
        ['sedentary', '/ˈsedənteri/', '久坐的；不爱活动的', 'A sedentary lifestyle increases the risk of heart disease.', '久坐的生活方式会增加心脏病风险。'],
      ],
    },
    {
      name: '训练与身体成分',
      tip: 'hyper- 过度 + trophy 生长 = hypertrophy 肌肥大；sarco- 肌肉 + -penia 缺少 = sarcopenia 肌少症；fast-twitch 快肌 / slow-twitch 慢肌。',
      words: [
        ['body composition', '/ˈbɑːdi ˌkɑːmpəˈzɪʃən/', '身体成分', 'Body composition describes how much fat and muscle you have.', '身体成分描述了你有多少脂肪和肌肉。'],
        ['lean body mass', '/liːn ˈbɑːdi mæs/', '瘦体重（去脂体重）', 'Strength training increases lean body mass.', '力量训练会增加瘦体重。'],
        ['body fat percentage', '/ˈbɑːdi fæt pərˈsentɪdʒ/', '体脂率', 'Her body fat percentage dropped after three months of training.', '经过三个月训练，她的体脂率下降了。'],
        ['muscle mass', '/ˈmʌsəl mæs/', '肌肉量', 'Muscle mass declines with age.', '肌肉量随年龄增长而下降。'],
        ['hypertrophy', '/haɪˈpɜːrtrəfi/', '（肌肉）肥大；增粗', 'Muscle hypertrophy requires training and enough protein.', '肌肉肥大需要训练和足够的蛋白质。'],
        ['sarcopenia', '/ˌsɑːrkəˈpiːniə/', '肌少症', 'Sarcopenia is the loss of muscle with aging.', '肌少症是随年龄增长出现的肌肉流失。'],
        ['fast-twitch fiber', '/ˈfæst twɪtʃ ˈfaɪbər/', '快肌纤维', 'Sprinters have many fast-twitch fibers.', '短跑运动员有很多快肌纤维。'],
        ['slow-twitch fiber', '/ˈsloʊ twɪtʃ ˈfaɪbər/', '慢肌纤维', 'A slow-twitch fiber is good at endurance work.', '慢肌纤维擅长耐力运动。'],
        ['resistance training', '/rɪˈzɪstəns ˈtreɪnɪŋ/', '抗阻训练', 'Resistance training makes muscles stronger.', '抗阻训练使肌肉更强壮。'],
        ['weight-bearing exercise', '/ˈweɪt ˌberɪŋ ˈeksərsaɪz/', '负重运动', 'Walking is a weight-bearing exercise that helps bones.', '步行是一种对骨骼有益的负重运动。'],
        ['strength', '/streŋθ/', '力量', 'Squats build leg strength.', '深蹲能增强腿部力量。'],
        ['power', '/ˈpaʊər/', '爆发力；功率', 'Jumping requires a lot of power.', '跳跃需要很强的爆发力。'],
        ['muscle protein synthesis', '/ˈmʌsəl ˈproʊtiːn ˈsɪnθəsɪs/', '肌肉蛋白质合成（MPS）', 'Eating protein after exercise boosts muscle protein synthesis.', '运动后摄入蛋白质能促进肌肉蛋白质合成。'],
        ['intensity', '/ɪnˈtensəti/', '强度', 'High intensity exercise burns mostly carbohydrates.', '高强度运动主要消耗碳水化合物。'],
        ['high-intensity interval training', '/ˌhaɪ ɪnˈtensəti ˈɪntərvəl ˈtreɪnɪŋ/', '高强度间歇训练（HIIT）', 'High-intensity interval training alternates hard and easy periods.', '高强度间歇训练交替进行高强度和低强度阶段。'],
        ['periodization', '/ˌpɪriədaɪˈzeɪʃən/', '周期化（训练）', 'Periodization changes training and nutrition across the season.', '周期化会在整个赛季中调整训练和营养。'],
        ['warm-up', '/ˈwɔːrm ʌp/', '热身', 'A good warm-up reduces the risk of injury.', '充分的热身能降低受伤风险。'],
        ['recovery', '/rɪˈkʌvəri/', '恢复', 'Sleep is essential for recovery.', '睡眠对恢复至关重要。'],
        ['overtraining', '/ˌoʊvərˈtreɪnɪŋ/', '过度训练', 'Overtraining can lead to injury and poor performance.', '过度训练会导致受伤和表现下降。'],
        ['muscle soreness', '/ˈmʌsəl ˈsɔːrnəs/', '肌肉酸痛', 'Muscle soreness often peaks two days after exercise.', '肌肉酸痛通常在运动后两天达到高峰。'],
      ],
    },
    {
      name: '运动补剂（ergogenic aids）',
      tip: 'ergo- 工作 + -genic 产生 = ergogenic 提高运动能力的；补剂要看证据和 third-party testing 第三方检测，避免 banned substance 违禁物质。',
      words: [
        ['dietary supplement', '/ˈdaɪəteri ˈsʌplɪmənt/', '膳食补充剂', 'A dietary supplement cannot replace a healthy diet.', '膳食补充剂不能替代健康的饮食。'],
        ['ergogenic aid', '/ˌɜːrɡoʊˈdʒenɪk eɪd/', '运动增力剂（提高运动表现的手段）', 'Caffeine is a well-known ergogenic aid.', '咖啡因是一种著名的运动增力剂。'],
        ['creatine', '/ˈkriːətiːn/', '肌酸', 'Creatine can improve short bursts of power.', '肌酸能提高短时爆发力。'],
        ['caffeine', '/kæˈfiːn/', '咖啡因', 'Caffeine can reduce the feeling of fatigue.', '咖啡因可以减轻疲劳感。'],
        ['whey protein', '/weɪ ˈproʊtiːn/', '乳清蛋白', 'Whey protein is digested quickly.', '乳清蛋白消化得很快。'],
        ['casein', '/ˈkeɪsiːn/', '酪蛋白', 'Casein is digested slowly, so some athletes take it before bed.', '酪蛋白消化较慢，所以有些运动员睡前服用。'],
        ['branched-chain amino acids', '/bræntʃt tʃeɪn əˈmiːnoʊ ˈæsɪdz/', '支链氨基酸（BCAA）', 'Leucine is one of the branched-chain amino acids.', '亮氨酸是支链氨基酸之一。'],
        ['beta-alanine', '/ˌbeɪtə ˈæləniːn/', 'β-丙氨酸', 'Beta-alanine may cause a tingling feeling in the skin.', 'β-丙氨酸可能会引起皮肤刺痒感。'],
        ['sodium bicarbonate', '/ˈsoʊdiəm baɪˈkɑːrbəneɪt/', '碳酸氢钠（小苏打）', 'Sodium bicarbonate can buffer acid during high-intensity exercise.', '碳酸氢钠能在高强度运动中缓冲酸。'],
        ['nitrate', '/ˈnaɪtreɪt/', '硝酸盐', 'Beetroot juice is high in nitrate.', '甜菜根汁富含硝酸盐。'],
        ['multivitamin', '/ˌmʌltiˈvaɪtəmɪn/', '复合维生素', 'A multivitamin may help if your diet is limited.', '如果饮食受限，复合维生素可能有帮助。'],
        ['dosage', '/ˈdoʊsɪdʒ/', '剂量', 'Always follow the recommended dosage.', '务必遵循推荐剂量。'],
        ['placebo', '/pləˈsiːboʊ/', '安慰剂', 'Some supplements work no better than a placebo.', '有些补剂的效果并不比安慰剂好。'],
        ['third-party testing', '/ˌθɜːrd ˈpɑːrti ˈtestɪŋ/', '第三方检测', 'Athletes should choose supplements with third-party testing.', '运动员应选择经过第三方检测的补剂。'],
        ['banned substance', '/bænd ˈsʌbstəns/', '违禁物质', 'Some supplements contain a banned substance.', '有些补剂含有违禁物质。'],
        ['anabolic steroid', '/ˌænəˈbɑːlɪk ˈstɪrɔɪd/', '合成代谢类固醇', 'Anabolic steroids are banned in sports.', '合成代谢类固醇在体育运动中是禁用的。'],
        ['doping', '/ˈdoʊpɪŋ/', '使用兴奋剂', 'Doping is banned in competitive sports.', '竞技体育禁止使用兴奋剂。'],
      ],
    },
    {
      name: '补水与电解质（hydr- 水）',
      tip: 'hydr- 表示“水”：hydration 补水、dehydration 脱水；hypo- 低 + natr（钠）+ -emia 血症 = hyponatremia 低钠血症。',
      words: [
        ['hydration', '/haɪˈdreɪʃən/', '水合；补水', 'Good hydration improves performance.', '充足的补水能提高运动表现。'],
        ['dehydration', '/ˌdiːhaɪˈdreɪʃən/', '脱水', 'Dehydration can cause headaches and dizziness.', '脱水会导致头痛和头晕。'],
        ['fluid replacement', '/ˈfluːɪd rɪˈpleɪsmənt/', '补液', 'Fluid replacement should match sweat losses.', '补液量应与出汗流失量相当。'],
        ['sweat rate', '/swet reɪt/', '出汗率', 'Weigh yourself before and after exercise to estimate your sweat rate.', '运动前后称体重可以估算你的出汗率。'],
        ['thirst', '/θɜːrst/', '口渴', 'Older adults may not feel thirst as strongly.', '老年人的口渴感可能没那么强烈。'],
        ['sports drink', '/spɔːrts drɪŋk/', '运动饮料', 'A sports drink provides fluid, sugar and electrolytes.', '运动饮料提供水分、糖和电解质。'],
        ['hyponatremia', '/ˌhaɪpoʊnəˈtriːmiə/', '低钠血症', 'Drinking too much plain water can cause hyponatremia.', '饮用过多的白开水可能导致低钠血症。'],
        ['muscle cramp', '/ˈmʌsəl kræmp/', '肌肉痉挛；抽筋', 'He got a muscle cramp in his calf during the game.', '他在比赛中小腿抽筋了。'],
        ['heat stroke', '/hiːt stroʊk/', '中暑（热射病）', 'Heat stroke is a medical emergency.', '中暑（热射病）是一种医疗急症。'],
      ],
    },
    {
      name: '营养时机与糖原（glycogen）',
      tip: '围绕 glycogen 糖原一起记：carbohydrate loading 加载 → glycogen depletion 耗竭 → hitting the wall 撞墙 → refueling / glycogen resynthesis 再合成。pre- 之前，post- 之后。',
      words: [
        ['nutrient timing', '/ˈnuːtriənt ˈtaɪmɪŋ/', '营养时机', 'Nutrient timing means eating the right food at the right time.', '营养时机是指在合适的时间吃合适的食物。'],
        ['carbohydrate loading', '/ˌkɑːrboʊˈhaɪdreɪt ˈloʊdɪŋ/', '碳水加载（糖原负荷法）', 'Marathon runners use carbohydrate loading before a race.', '马拉松跑者在比赛前进行碳水加载。'],
        ['glycogen depletion', '/ˈɡlaɪkədʒən dɪˈpliːʃən/', '糖原耗竭', 'Glycogen depletion makes you slow down suddenly.', '糖原耗竭会让你突然慢下来。'],
        ['hitting the wall', '/ˈhɪtɪŋ ðə wɔːl/', '撞墙（耐力运动中能量耗尽）', 'Many marathon runners experience hitting the wall at around 30 kilometers.', '许多马拉松跑者在30公里左右会“撞墙”。'],
        ['glycogen resynthesis', '/ˈɡlaɪkədʒən riːˈsɪnθəsɪs/', '糖原再合成', 'Glycogen resynthesis is fastest in the first hours after exercise.', '糖原再合成在运动后最初几小时最快。'],
        ['refueling', '/riːˈfjuːəlɪŋ/', '补充能量', 'Refueling with carbs and protein speeds up recovery.', '用碳水和蛋白质补充能量能加快恢复。'],
        ['energy gel', '/ˈenərdʒi dʒel/', '能量胶', 'Runners take an energy gel every 45 minutes during a marathon.', '跑者在马拉松中每45分钟吃一支能量胶。'],
        ['pre-workout meal', '/ˌpriː ˈwɜːrkaʊt miːl/', '训练前餐', 'Eat a pre-workout meal two to three hours before training.', '在训练前两到三小时吃训练前餐。'],
        ['post-workout', '/ˌpoʊst ˈwɜːrkaʊt/', '训练后的', 'A post-workout snack should contain protein.', '训练后的加餐应该含有蛋白质。'],
      ],
    },
    {
      name: '特殊运动人群与风险',
      tip: 'a- 无 + men 月经 + -rrhea 流 = amenorrhea 闭经；女运动员三联征 = 低能量可用性 + 闭经 + 骨密度低，现扩展为 RED-S。',
      words: [
        ['low energy availability', '/loʊ ˈenərdʒi əˌveɪləˈbɪləti/', '低能量可用性', 'Low energy availability can harm bone health in athletes.', '低能量可用性会损害运动员的骨骼健康。'],
        ['female athlete triad', '/ˈfiːmeɪl ˈæθliːt ˈtraɪæd/', '女运动员三联征', 'The female athlete triad includes low energy, amenorrhea and low bone density.', '女运动员三联征包括低能量、闭经和骨密度低。'],
        ['relative energy deficiency in sport', '/ˈrelətɪv ˈenərdʒi dɪˈfɪʃənsi ɪn spɔːrt/', '运动相对能量不足（RED-S）', 'Relative energy deficiency in sport affects both male and female athletes.', '运动相对能量不足会影响男女运动员。'],
        ['amenorrhea', '/eɪˌmenəˈriːə/', '闭经', 'Amenorrhea in athletes is often caused by low energy intake.', '运动员闭经常由能量摄入不足引起。'],
        ['stress fracture', '/stres ˈfræktʃər/', '应力性骨折', 'Low bone density increases the risk of a stress fracture.', '骨密度低会增加应力性骨折的风险。'],
        ['making weight', '/ˈmeɪkɪŋ weɪt/', '赛前降体重（达到级别体重）', 'Wrestlers often struggle with making weight.', '摔跤运动员常常为赛前降体重而苦恼。'],
      ],
    },
  ],
});
